-- 089_receipt_extra_costs.sql
-- 명세서(영수번호) 단위 기타 비용 저장: 통관비, 보관료, 기타 수수료 등.

create table if not exists public.receipt_extra_costs (
  id bigint generated by default as identity primary key,
  route text not null,
  shipment_year integer not null,
  voyage text not null,
  receipt_number text not null,
  cost_name text not null,
  amount_usd numeric(14,2) not null check (amount_usd >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_receipt_extra_costs_lookup
  on public.receipt_extra_costs(route, shipment_year, voyage, receipt_number);

alter table public.receipt_extra_costs enable row level security;

create or replace function public.list_receipt_extra_costs(
  p_route text,p_year integer,p_voyage text,p_receipt_number text
) returns table(id bigint,cost_name text,amount_usd numeric)
language sql security definer set search_path=public as $$
  select e.id,e.cost_name,e.amount_usd
  from public.receipt_extra_costs e
  where e.route=btrim(p_route)
    and e.shipment_year=p_year
    and regexp_replace(coalesce(e.voyage,''),'[^0-9]','','g')
        = regexp_replace(coalesce(p_voyage,''),'[^0-9]','','g')
    and btrim(e.receipt_number)=btrim(p_receipt_number)
  order by e.id;
$$;

create or replace function public.save_receipt_extra_cost(
  p_id bigint,
  p_route text,
  p_year integer,
  p_voyage text,
  p_receipt_number text,
  p_cost_name text,
  p_amount_usd numeric
) returns bigint
language plpgsql security definer set search_path=public as $$
declare
  v_id bigint;
begin
  if auth.uid() is null or not exists(
    select 1 from public.profiles p
    where p.id=auth.uid() and p.role in ('admin','staff')
  ) then
    raise exception '기타 비용 수정 권한이 없습니다.';
  end if;
  if coalesce(btrim(p_cost_name),'')='' then raise exception '비용 이름을 입력해 주세요.'; end if;
  if coalesce(p_amount_usd,0)<0 then raise exception '금액을 확인해 주세요.'; end if;

  if p_id is null then
    insert into public.receipt_extra_costs(
      route,shipment_year,voyage,receipt_number,cost_name,amount_usd
    ) values(
      btrim(p_route),p_year,btrim(p_voyage),btrim(p_receipt_number),
      btrim(p_cost_name),p_amount_usd
    ) returning id into v_id;
  else
    update public.receipt_extra_costs
    set cost_name=btrim(p_cost_name),
        amount_usd=p_amount_usd,
        updated_at=now()
    where id=p_id
    returning id into v_id;
    if v_id is null then raise exception '기타 비용 항목을 찾을 수 없습니다.'; end if;
  end if;
  return v_id;
end $$;

create or replace function public.delete_receipt_extra_cost(p_id bigint)
returns void
language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null or not exists(
    select 1 from public.profiles p
    where p.id=auth.uid() and p.role in ('admin','staff')
  ) then
    raise exception '기타 비용 삭제 권한이 없습니다.';
  end if;
  delete from public.receipt_extra_costs where id=p_id;
end $$;

revoke all on function public.list_receipt_extra_costs(text,integer,text,text) from public;
revoke all on function public.save_receipt_extra_cost(bigint,text,integer,text,text,text,numeric) from public;
revoke all on function public.delete_receipt_extra_cost(bigint) from public;
grant execute on function public.list_receipt_extra_costs(text,integer,text,text) to authenticated,service_role;
grant execute on function public.save_receipt_extra_cost(bigint,text,integer,text,text,text,numeric) to authenticated,service_role;
grant execute on function public.delete_receipt_extra_cost(bigint) to authenticated,service_role;
