-- Invoice suffix recovery search for member cargo with incorrect recipient data.
-- The lookup only returns masked recipient data and requires an authenticated
-- member plus at least four normalized invoice characters.

create table if not exists public.invoice_suffix_search_audit (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  queried_at timestamptz not null default now()
);

alter table public.invoice_suffix_search_audit enable row level security;
revoke all on table public.invoice_suffix_search_audit from public, anon, authenticated;

create index if not exists invoice_suffix_search_audit_requester_time_idx
  on public.invoice_suffix_search_audit (requester_id, queried_at desc);

create table if not exists public.invoice_correction_requests (
  id bigint generated by default as identity primary key,
  shipment_id bigint not null references public.shipments(id) on delete cascade,
  requester_id uuid not null references auth.users(id) on delete cascade,
  invoice_suffix text not null,
  claimant_name text not null,
  claimant_phone text not null,
  note text not null default '',
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.invoice_correction_requests enable row level security;
revoke all on table public.invoice_correction_requests from public, anon, authenticated;

create unique index if not exists invoice_correction_one_pending_per_member_idx
  on public.invoice_correction_requests (shipment_id, requester_id)
  where status = 'pending';

create or replace function public.search_shipments_by_invoice_suffix(
  p_invoice_suffix text
)
returns table (
  id bigint,
  route text,
  shipment_year integer,
  voyage text,
  box_number text,
  invoice_number text,
  consignee_name text,
  consignee_phone text,
  quantity integer,
  weight_kg numeric,
  length_cm numeric,
  width_cm numeric,
  height_cm numeric,
  received_at date,
  status text,
  recipient_unknown boolean,
  invoice_suffix_match boolean,
  correction_pending boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_suffix text := regexp_replace(lower(coalesce(p_invoice_suffix, '')), '[^a-z0-9]', '', 'g');
  v_recent_count integer;
begin
  if v_uid is null then
    raise exception '로그인이 필요합니다.';
  end if;
  if public.current_role() <> 'member' then
    raise exception '일반 회원의 송장번호 복구 검색 전용 기능입니다.';
  end if;
  if length(v_suffix) < 4 then
    raise exception '송장번호 뒤 4자리 이상을 입력해 주세요.';
  end if;
  if length(v_suffix) > 32 then
    raise exception '송장번호가 너무 깁니다.';
  end if;

  select count(*) into v_recent_count
  from public.invoice_suffix_search_audit a
  where a.requester_id = v_uid
    and a.queried_at >= now() - interval '1 hour';

  if v_recent_count >= 30 then
    raise exception '송장번호 검색 횟수를 초과했습니다. 잠시 후 다시 시도해 주세요.';
  end if;

  insert into public.invoice_suffix_search_audit(requester_id) values (v_uid);

  return query
  select
    s.id,
    s.route,
    s.shipment_year,
    s.voyage,
    s.box_number,
    '••••' || right(regexp_replace(lower(coalesce(s.invoice_number, '')), '[^a-z0-9]', '', 'g'), length(v_suffix)),
    case when s.recipient_unknown then '수취인 불명' else '등록 정보 불일치 · 관리자 확인 필요' end,
    ''::text,
    s.quantity,
    s.weight_kg,
    s.length_cm,
    s.width_cm,
    s.height_cm,
    s.received_at,
    s.status,
    s.recipient_unknown,
    true,
    exists (
      select 1 from public.invoice_correction_requests r
      where r.shipment_id = s.id
        and r.requester_id = v_uid
        and r.status = 'pending'
    )
  from public.shipments s
  where s.deleted_at is null
    and s.deletion_requested_at is null
    and right(
      regexp_replace(lower(coalesce(s.invoice_number, '')), '[^a-z0-9]', '', 'g'),
      length(v_suffix)
    ) = v_suffix
  order by s.shipment_year desc nulls last, s.received_at desc nulls last, s.id desc
  limit 20;
end;
$$;

create or replace function public.create_invoice_correction_request(
  p_shipment_id bigint,
  p_invoice_suffix text,
  p_claimant_name text,
  p_claimant_phone text,
  p_note text default ''
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_suffix text := regexp_replace(lower(coalesce(p_invoice_suffix, '')), '[^a-z0-9]', '', 'g');
  v_id bigint;
begin
  if v_uid is null or public.current_role() <> 'member' then
    raise exception '일반 회원 로그인이 필요합니다.';
  end if;
  if length(v_suffix) < 4 then
    raise exception '송장번호 뒤 4자리 이상을 입력해 주세요.';
  end if;
  if nullif(btrim(p_claimant_name), '') is null
     or length(public.only_digits(p_claimant_phone)) < 8 then
    raise exception '본인 이름과 연락처를 정확히 입력해 주세요.';
  end if;
  if not exists (
    select 1 from public.shipments s
    where s.id = p_shipment_id
      and s.deleted_at is null
      and s.deletion_requested_at is null
      and right(
        regexp_replace(lower(coalesce(s.invoice_number, '')), '[^a-z0-9]', '', 'g'),
        length(v_suffix)
      ) = v_suffix
  ) then
    raise exception '송장번호가 일치하는 화물을 찾을 수 없습니다.';
  end if;
  if exists (
    select 1 from public.invoice_correction_requests r
    where r.shipment_id = p_shipment_id
      and r.requester_id = v_uid
      and r.status = 'pending'
  ) then
    raise exception '이미 관리자 확인 대기 중인 요청이 있습니다.';
  end if;

  insert into public.invoice_correction_requests(
    shipment_id, requester_id, invoice_suffix, claimant_name, claimant_phone, note
  ) values (
    p_shipment_id, v_uid, v_suffix, btrim(p_claimant_name), btrim(p_claimant_phone), coalesce(p_note, '')
  ) returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.admin_list_invoice_correction_requests()
returns table (
  request_id bigint,
  shipment_id bigint,
  route text,
  shipment_year integer,
  voyage text,
  box_number text,
  invoice_number text,
  current_name text,
  current_phone text,
  claimant_name text,
  claimant_phone text,
  requester_email text,
  note text,
  data_locked boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.current_role() <> 'admin' then
    raise exception '관리자(총괄) 권한이 필요합니다.';
  end if;

  return query
  select
    r.id,
    r.shipment_id,
    s.route,
    s.shipment_year,
    s.voyage,
    s.box_number,
    s.invoice_number,
    s.consignee_name,
    s.consignee_phone,
    r.claimant_name,
    r.claimant_phone,
    coalesce(p.email, ''),
    r.note,
    s.data_locked,
    r.created_at
  from public.invoice_correction_requests r
  join public.shipments s on s.id = r.shipment_id
  left join public.profiles p on p.id = r.requester_id
  where r.status = 'pending'
  order by r.created_at;
end;
$$;

create or replace function public.admin_review_invoice_correction_request(
  p_request_id bigint,
  p_action text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.invoice_correction_requests%rowtype;
begin
  if public.current_role() <> 'admin' then
    raise exception '관리자(총괄) 권한이 필요합니다.';
  end if;
  if p_action not in ('approve', 'reject') then
    raise exception '처리 방식이 올바르지 않습니다.';
  end if;

  select * into v_request
  from public.invoice_correction_requests
  where id = p_request_id and status = 'pending'
  for update;

  if not found then
    raise exception '대기 중인 요청을 찾을 수 없습니다.';
  end if;

  if p_action = 'approve' then
    update public.shipments
    set consignee_name = btrim(v_request.claimant_name),
        consignee_phone = btrim(v_request.claimant_phone),
        recipient_unknown = false,
        manual_uncertain = false,
        recipient_unknown_confirmed_at = case when recipient_unknown then now() else recipient_unknown_confirmed_at end,
        recipient_unknown_confirmed_by = case when recipient_unknown then auth.uid() else recipient_unknown_confirmed_by end,
        updated_at = now()
    where id = v_request.shipment_id;
  end if;

  update public.invoice_correction_requests
  set status = case when p_action = 'approve' then 'approved' else 'rejected' end,
      reviewed_by = auth.uid(),
      reviewed_at = now()
  where id = p_request_id;

  if p_action = 'approve' then
    update public.invoice_correction_requests
    set status = 'rejected', reviewed_by = auth.uid(), reviewed_at = now()
    where shipment_id = v_request.shipment_id
      and id <> p_request_id
      and status = 'pending';
  end if;
end;
$$;

revoke execute on function public.search_shipments_by_invoice_suffix(text) from public, anon;
revoke execute on function public.create_invoice_correction_request(bigint, text, text, text, text) from public, anon;
revoke execute on function public.admin_list_invoice_correction_requests() from public, anon;
revoke execute on function public.admin_review_invoice_correction_request(bigint, text) from public, anon;

grant execute on function public.search_shipments_by_invoice_suffix(text) to authenticated;
grant execute on function public.create_invoice_correction_request(bigint, text, text, text, text) to authenticated;
grant execute on function public.admin_list_invoice_correction_requests() to authenticated;
grant execute on function public.admin_review_invoice_correction_request(bigint, text) to authenticated;

