-- Patch165 / 097
-- Customer discount confirmation + receipt priority + zone override rules.

create table if not exists public.customer_zone_overrides (
  id bigint generated by default as identity primary key,
  route_key text not null,
  customer_name text not null,
  zone text not null default '102',
  source_type text not null default 'base_excel',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(route_key, customer_name, source_type)
);

create index if not exists idx_customer_zone_overrides_lookup
  on public.customer_zone_overrides(route_key, active, customer_name);

alter table public.customer_zone_overrides enable row level security;

drop policy if exists customer_zone_overrides_read_authenticated
  on public.customer_zone_overrides;
create policy customer_zone_overrides_read_authenticated
  on public.customer_zone_overrides for select
  to authenticated
  using (true);

create or replace function public.admin_replace_base_zone_overrides(
  p_route_key text,
  p_names jsonb
)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare
  v_name text;
  v_count integer:=0;
begin
  if coalesce(btrim(p_route_key),'')='' then return 0; end if;

  delete from public.customer_zone_overrides
  where route_key=btrim(p_route_key)
    and source_type='base_excel';

  for v_name in
    select distinct btrim(value)
    from jsonb_array_elements_text(coalesce(p_names,'[]'::jsonb))
    where btrim(value)<>''
  loop
    insert into public.customer_zone_overrides(
      route_key,customer_name,zone,source_type,active,updated_at
    ) values(
      btrim(p_route_key),v_name,'102','base_excel',true,now()
    )
    on conflict(route_key,customer_name,source_type)
    do update set zone='102',active=true,updated_at=now();
    v_count:=v_count+1;
  end loop;

  return v_count;
end
$$;

revoke all on function public.admin_replace_base_zone_overrides(text,jsonb) from public;
grant execute on function public.admin_replace_base_zone_overrides(text,jsonb)
  to authenticated,service_role;

create or replace function public.admin_list_discount_rules_waiting_for_phone()
returns setof jsonb
language sql
stable
security definer
set search_path=public
as $$
  select jsonb_build_object(
    'id',r.id,
    'route_key',coalesce(r.route_key,''),
    'customer_name',coalesce(r.customer_name,''),
    'company_name',coalesce(r.company_name,''),
    'group_name',coalesce(r.group_name,''),
    'discount_percent',coalesce(r.discount_percent,0),
    'notes',coalesce(r.notes,''),
    'source_detail',coalesce(r.source_detail,''),
    'candidate_phone',coalesce(c.candidate_phone,'')
  )
  from public.customer_rate_overrides r
  left join lateral (
    select btrim(coalesce(s.consignee_phone,'')) candidate_phone
    from public.shipments s
    where public.normalize_phone(s.consignee_phone)<>''
      and (r.route_key='all' or public.route_base_key_for_label(s.route)=r.route_key)
      and (
        public.normalize_person_name(s.consignee_name)=public.normalize_person_name(r.customer_name)
        or (
          coalesce(r.company_name,'')<>''
          and public.normalize_person_name(s.consignee_name)=public.normalize_person_name(r.company_name)
        )
      )
    order by s.received_at desc nulls last,s.id desc
    limit 1
  ) c on true
  where coalesce(r.active,false)=false
    and public.normalize_phone(r.phone)=''
    and coalesce(r.discount_percent,0)>0
    and public.normalize_person_name(r.customer_name) not in (
      public.normalize_person_name('박성호'),
      public.normalize_person_name('박성호 대표')
    )
  order by r.route_key,r.group_name,r.customer_name,r.id
$$;

revoke all on function public.admin_list_discount_rules_waiting_for_phone() from public;
grant execute on function public.admin_list_discount_rules_waiting_for_phone()
  to authenticated,service_role;

create or replace function public.admin_confirm_discount_rule(
  p_id bigint,
  p_customer_name text,
  p_company_name text,
  p_phone text,
  p_group_name text,
  p_discount_percent numeric,
  p_notes text
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  v_phone text:=public.normalize_phone(p_phone);
begin
  if v_phone='' then
    raise exception '전화번호를 입력해야 할인 고객으로 확정할 수 있습니다.';
  end if;
  if p_discount_percent is null or p_discount_percent<0 or p_discount_percent>1 then
    raise exception '할인율은 0~100%% 범위여야 합니다.';
  end if;

  update public.customer_rate_overrides
  set customer_name=btrim(coalesce(p_customer_name,'')),
      company_name=btrim(coalesce(p_company_name,'')),
      phone=v_phone,
      group_name=btrim(coalesce(p_group_name,'')),
      discount_percent=p_discount_percent,
      notes=btrim(coalesce(p_notes,'')),
      active=true
  where id=p_id;

  if not found then
    raise exception '할인 규칙을 찾지 못했습니다.';
  end if;

  perform public.admin_refresh_shipment_special_notes();
end
$$;

revoke all on function public.admin_confirm_discount_rule(bigint,text,text,text,text,numeric,text) from public;
grant execute on function public.admin_confirm_discount_rule(bigint,text,text,text,text,numeric,text)
  to authenticated,service_role;

-- Patch165 receipt/zone normalization.
-- Existing locked/manual anchors are preserved by normal normalize calls.
-- New unassigned groups are created in the required order:
-- province delivery -> city delivery -> other names -> Park Seongho(100) -> unknown(XX).
create or replace function public.normalize_shipment_batch(
  p_route text,
  p_year integer,
  p_voyage text
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  v_route_key text;
  v_prefix text;
  v_voyage text:=lpad(regexp_replace(coalesce(p_voyage,''),'[^0-9]','','g'),2,'0');
  v_next integer;
  r record;
  v_receipt text;
begin
  if coalesce(btrim(p_route),'')='' or p_year is null or coalesce(v_voyage,'')='' then
    return;
  end if;
  if current_setting('lkgroup.normalizing_shipments',true)='1' then return; end if;
  perform set_config('lkgroup.normalizing_shipments','1',true);

  select rd.route_key,rd.receipt_prefix
    into v_route_key,v_prefix
  from public.route_definitions rd
  where rd.display_name=btrim(p_route) or rd.route_key=btrim(p_route)
  order by case when rd.display_name=btrim(p_route) then 0 else 1 end
  limit 1;

  if coalesce(btrim(v_prefix),'')='' then
    perform set_config('lkgroup.normalizing_shipments','',true);
    return;
  end if;

  drop table if exists pg_temp._ng;
  drop table if exists pg_temp._nr;
  drop table if exists pg_temp._nq;

  create temporary table _ng on commit drop as
  with b as (
    select
      s.id,s.data_locked,s.receipt_number,
      s.consignee_name,s.consignee_phone,
      greatest(coalesce(s.quantity,1),1)::integer qty,
      lower(regexp_replace(btrim(coalesce(s.consignee_name,'')),'\s+',' ','g')) name_key,
      regexp_replace(coalesce(s.consignee_phone,''),'[^0-9]','','g') digits,
      public.lk_recipient_name_uncertain(s.consignee_name) name_bad,
      public.lk_recipient_phone_uncertain(s.consignee_phone) phone_bad,
      public.lk_recipient_true_unknown(s.consignee_name,s.consignee_phone) is_unknown
    from public.shipments s
    where s.route=p_route
      and s.shipment_year=p_year
      and lpad(regexp_replace(coalesce(s.voyage,''),'[^0-9]','','g'),2,'0')=v_voyage
      and s.deletion_requested_at is null
  ), p as (
    select *,case when not phone_bad and length(digits)>=7 then right(digits,8) else '' end phone_key
    from b
  ), st as (
    select name_key,count(distinct nullif(phone_key,'')) phone_count,min(nullif(phone_key,'')) only_phone
    from p where not is_unknown and not name_bad group by name_key
  )
  select p.*,
    case
      when is_unknown then '__UNKNOWN__:'||id::text
      when not phone_bad and phone_key<>'' then
        case when name_bad then 'PHONE|'||phone_key else 'NAMEPHONE|'||name_key||'|'||phone_key end
      when not name_bad and coalesce(st.phone_count,0)=1 then 'NAMEPHONE|'||name_key||'|'||st.only_phone
      when not name_bad then 'NAME|'||name_key
      else '__UNKNOWN__:'||id::text
    end identity_key,
    2::integer receipt_priority
  from p left join st using(name_key);

  update _ng g
  set receipt_priority=case
    when public.normalize_person_name(g.consignee_name) in (
      public.normalize_person_name('박성호'),public.normalize_person_name('박성호 대표')
    ) then 8
    else coalesce((
      select case when d.delivery_type='province' then 0 else 1 end
      from public.local_delivery_profiles d
      where d.active=true and d.route_key=v_route_key
        and public.phone_matches(d.phone,g.consignee_phone)
        and (
          public.normalize_person_name(d.customer_name)=public.normalize_person_name(g.consignee_name)
          or (coalesce(d.alternate_name,'')<>'' and public.normalize_person_name(d.alternate_name)=public.normalize_person_name(g.consignee_name))
          or (coalesce(d.company_name,'')<>'' and public.normalize_person_name(d.company_name)=public.normalize_person_name(g.consignee_name))
        )
      order by d.preferred desc,d.source_no nulls last,d.id
      limit 1
    ),2)
  end;

  update public.shipments s
  set recipient_unknown=true,
      receipt_number=case when v_route_key in ('kr_la_sea','kr_la_air') then btrim(v_prefix)||' XX' else btrim(v_prefix)||'XX' end,
      unloading_zone='F'
  from _ng g
  where s.id=g.id and g.is_unknown and not coalesce(g.data_locked,false);

  update public.shipments s
  set recipient_unknown=false
  from _ng g
  where s.id=g.id and not g.is_unknown and not coalesce(g.data_locked,false);

  -- Park Seongho representative is the reserved 100 receipt for every route prefix.
  update public.shipments s
  set receipt_number=case when v_route_key in ('kr_la_sea','kr_la_air') then btrim(v_prefix)||' 100' else btrim(v_prefix)||'100' end
  from _ng g
  where s.id=g.id and not g.is_unknown and not coalesce(g.data_locked,false)
    and public.normalize_person_name(g.consignee_name) in (
      public.normalize_person_name('박성호'),public.normalize_person_name('박성호 대표')
    );

  create temporary table _nr(identity_key text primary key,receipt_number text) on commit drop;

  insert into _nr(identity_key,receipt_number)
  select identity_key,min(btrim(receipt_number))
  from _ng
  where not is_unknown and coalesce(data_locked,false) and coalesce(btrim(receipt_number),'')<>''
  group by identity_key on conflict(identity_key) do nothing;

  insert into _nr(identity_key,receipt_number)
  select g.identity_key,min(btrim(s.receipt_number))
  from _ng g
  join public.shipments s on s.id=g.id
  join (
    select btrim(s2.receipt_number) receipt,count(distinct g2.identity_key) n
    from _ng g2 join public.shipments s2 on s2.id=g2.id
    where not g2.is_unknown and coalesce(btrim(s2.receipt_number),'')<>''
    group by btrim(s2.receipt_number)
    having count(distinct g2.identity_key)=1
  ) u on u.receipt=btrim(s.receipt_number)
  where not g.is_unknown and not coalesce(g.data_locked,false)
    and not exists(select 1 from _nr x where x.identity_key=g.identity_key)
  group by g.identity_key
  on conflict(identity_key) do nothing;

  v_next:=1;
  for r in
    select identity_key,min(receipt_priority) priority,min(name_key) sort_name,min(id) first_id
    from _ng g
    where not is_unknown
      and not exists(select 1 from _nr x where x.identity_key=g.identity_key)
    group by identity_key
    order by min(receipt_priority),min(name_key),min(id)
  loop
    loop
      if v_next=100 then v_next:=101; end if;
      if v_route_key in ('kr_la_sea','kr_la_air') then
        v_receipt:=btrim(v_prefix)||' '||lpad(v_next::text,2,'0');
      else
        v_receipt:=btrim(v_prefix)||lpad(v_next::text,2,'0');
      end if;
      v_next:=v_next+1;
      exit when not exists(
        select 1 from public.shipments s
        where s.route=p_route and s.shipment_year=p_year
          and lpad(regexp_replace(coalesce(s.voyage,''),'[^0-9]','','g'),2,'0')=v_voyage
          and s.deletion_requested_at is null and btrim(coalesce(s.receipt_number,''))=v_receipt
      ) and not exists(select 1 from _nr n where btrim(coalesce(n.receipt_number,''))=v_receipt);
    end loop;
    insert into _nr(identity_key,receipt_number) values(r.identity_key,v_receipt);
  end loop;

  update public.shipments s
  set receipt_number=n.receipt_number
  from _ng g join _nr n using(identity_key)
  where s.id=g.id and not g.is_unknown and not coalesce(g.data_locked,false);

  create temporary table _nq on commit drop as
  select btrim(s.receipt_number) receipt,sum(g.qty)::integer total_qty
  from _ng g join public.shipments s on s.id=g.id
  where not g.is_unknown and coalesce(btrim(s.receipt_number),'')<>''
  group by btrim(s.receipt_number);

  update public.shipments s
  set unloading_zone=case
    -- BASE Excel fixed classification is the highest priority.
    when exists(
      select 1 from public.customer_zone_overrides z
      where z.active=true and (z.route_key=v_route_key or z.route_key='all') and z.zone='102'
        and public.normalize_person_name(z.customer_name)=public.normalize_person_name(g.consignee_name)
    ) then '102'
    -- Kim Yosep / Beauty Panda and every city/province delivery are forced to F.
    when public.normalize_person_name(g.consignee_name) like '%'||public.normalize_person_name('김요셉')||'%'
      or lower(coalesce(g.consignee_name,'')) like '%beauty panda%'
      or coalesce(g.consignee_name,'') like '%뷰티판다%'
      or exists(
        select 1 from public.local_delivery_profiles d
        where d.active=true and d.route_key=v_route_key
          and public.phone_matches(d.phone,g.consignee_phone)
          and (
            public.normalize_person_name(d.customer_name)=public.normalize_person_name(g.consignee_name)
            or (coalesce(d.alternate_name,'')<>'' and public.normalize_person_name(d.alternate_name)=public.normalize_person_name(g.consignee_name))
            or (coalesce(d.company_name,'')<>'' and public.normalize_person_name(d.company_name)=public.normalize_person_name(g.consignee_name))
          )
      ) then 'F'
    when v_route_key='kr_la_air' then '102'
    when q.total_qty>=20 then 'F'
    when q.total_qty>=10 then 'C'
    when q.total_qty>=5 then 'B'
    else 'A'
  end
  from _ng g,_nq q
  where s.id=g.id and not g.is_unknown and not coalesce(g.data_locked,false)
    and q.receipt=btrim(s.receipt_number);

  perform set_config('lkgroup.normalizing_shipments','',true);
exception when others then
  perform set_config('lkgroup.normalizing_shipments','',true);
  raise;
end
$$;

revoke all on function public.normalize_shipment_batch(text,integer,text) from public;
grant execute on function public.normalize_shipment_batch(text,integer,text)
  to authenticated,service_role;

-- Called once after a full Excel upload. If the source workbook had no receipt numbers,
-- unlocked auto receipts are re-created once in the required business order.
create or replace function public.admin_finalize_excel_batch_rules(
  p_route text,
  p_year integer,
  p_voyage text,
  p_resequence boolean default false
)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  v_route_key text;
  v_prefix text;
  v_voyage text:=lpad(regexp_replace(coalesce(p_voyage,''),'[^0-9]','','g'),2,'0');
begin
  select rd.route_key,rd.receipt_prefix into v_route_key,v_prefix
  from public.route_definitions rd
  where rd.display_name=btrim(p_route) or rd.route_key=btrim(p_route)
  order by case when rd.display_name=btrim(p_route) then 0 else 1 end limit 1;

  if coalesce(v_route_key,'')='' then return; end if;

  if coalesce(p_resequence,false) then
    perform set_config('lkgroup.normalizing_shipments','1',true);
    update public.shipments s
    set receipt_number=null
    where s.route=p_route and s.shipment_year=p_year
      and lpad(regexp_replace(coalesce(s.voyage,''),'[^0-9]','','g'),2,'0')=v_voyage
      and s.deletion_requested_at is null and not coalesce(s.data_locked,false)
      and not public.lk_recipient_true_unknown(s.consignee_name,s.consignee_phone)
      and public.normalize_person_name(s.consignee_name) not in (
        public.normalize_person_name('박성호'),public.normalize_person_name('박성호 대표')
      );

    update public.shipments s
    set receipt_number=case when v_route_key in ('kr_la_sea','kr_la_air') then btrim(v_prefix)||' 100' else btrim(v_prefix)||'100' end
    where s.route=p_route and s.shipment_year=p_year
      and lpad(regexp_replace(coalesce(s.voyage,''),'[^0-9]','','g'),2,'0')=v_voyage
      and s.deletion_requested_at is null and not coalesce(s.data_locked,false)
      and public.normalize_person_name(s.consignee_name) in (
        public.normalize_person_name('박성호'),public.normalize_person_name('박성호 대표')
      );
    perform set_config('lkgroup.normalizing_shipments','',true);
  end if;

  perform public.normalize_shipment_batch(p_route,p_year,p_voyage);
  perform public.admin_refresh_shipment_special_notes();
exception when others then
  perform set_config('lkgroup.normalizing_shipments','',true);
  raise;
end
$$;

revoke all on function public.admin_finalize_excel_batch_rules(text,integer,text,boolean) from public;
grant execute on function public.admin_finalize_excel_batch_rules(text,integer,text,boolean)
  to authenticated,service_role;

-- Park Seongho representative: absolute 100% discount override in document remarks.
create or replace function public.compute_shipment_special_note(
  p_route text,
  p_name text,
  p_phone text
)
returns text
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  v_route_key text := public.route_base_key_for_label(p_route);
  v_group text := '';
  v_discount numeric := 0;
  v_delivery text := '';
  v_discount_text text := '';
begin
  if public.normalize_person_name(p_name) in (
    public.normalize_person_name('박성호'),public.normalize_person_name('박성호 대표')
  ) then
    v_group:='대표 고정 100% 할인';
    v_discount:=1;
  elsif public.normalize_phone(p_phone) <> '' and public.normalize_person_name(p_name) <> '' then
    select coalesce(group_name,''),coalesce(discount_percent,0)
      into v_group,v_discount
    from public.customer_rate_overrides r
    where r.active=true and (r.route_key=v_route_key or r.route_key='all')
      and public.phone_matches(r.phone,p_phone)
      and (
        public.normalize_person_name(r.customer_name)=public.normalize_person_name(p_name)
        or (coalesce(r.company_name,'')<>'' and public.normalize_person_name(r.company_name)=public.normalize_person_name(p_name))
      )
    order by case when r.route_key=v_route_key then 0 else 1 end,r.id limit 1;
  end if;

  if public.normalize_phone(p_phone)<>'' and public.normalize_person_name(p_name)<>'' then
    select case
      when d.delivery_type='city' and coalesce(d.paid_by,'') like '%선결제%' then '시내배송(선결제)'
      when d.delivery_type='city' then '시내배송'
      when coalesce(d.paid_by,'') like '%선결제%' then '지방배송(선결제)'
      else '지방배송'
    end
      into v_delivery
    from public.local_delivery_profiles d
    where d.active=true and d.route_key=v_route_key and public.phone_matches(d.phone,p_phone)
      and (
        public.normalize_person_name(d.customer_name)=public.normalize_person_name(p_name)
        or (coalesce(d.alternate_name,'')<>'' and public.normalize_person_name(d.alternate_name)=public.normalize_person_name(p_name))
        or (coalesce(d.company_name,'')<>'' and public.normalize_person_name(d.company_name)=public.normalize_person_name(p_name))
      )
    order by d.preferred desc,d.source_no nulls last,d.id limit 1;
  end if;

  if coalesce(v_discount,0)>0 then
    v_discount_text:=concat(
      case when lower(v_group) like '%특별%' then '특별할인 ' else '할인 ' end,
      trim(to_char(v_discount*100,'FM999990.##')),'% 적용'
    );
  end if;
  return concat_ws(' / ',nullif(v_discount_text,''),nullif(v_delivery,''));
end
$$;

update public.shipments s
set special_note_auto=public.compute_shipment_special_note(s.route,s.consignee_name,s.consignee_phone);
