$ErrorActionPreference = "Stop"
Write-Host ""
Write-Host "Patch160 파일 배치 완료"
Write-Host ""
Write-Host "이번 Patch는 Flutter 파일 수정 없음."
Write-Host "1) 영수번호 자동 생성: MAX+1 -> 가장 작은 빈 번호 우선"
Write-Host "2) 잠금/기존/수동 영수번호는 강제 재번호하지 않음"
Write-Host "3) 새 화물/정상화/재업로드/관리자 수정 모두 중앙 normalize 공통 적용"
Write-Host "4) admin_receipt_number_gaps() 진단 함수 추가"
Write-Host ""
Write-Host "Supabase SQL Editor에서 supabase_092_receipt_sequence_no_gap.sql 전체 실행"
