from pathlib import Path
cwd=Path.cwd()
def rd(p): return p.read_text(encoding='utf-8-sig')
def wr(p,s): p.write_text(s,encoding='utf-8')

p=cwd/'lib/services/excel_import_service.dart'
s=rd(p)
start=s.find('  String _discountGroupNameForSheet(')
end=s.find('  Future<int> _importStatementShareRules(',start)
if start<0 or end<0: raise SystemExit('discount group helper block not found')
helper="  String _discountGroupNameForSheet(\n    List<List<String>> sheet, {\n    required int headerRow,\n    required int customerColumn,\n  }) {\n    String clean(String raw) {\n      var text = raw.trim();\n      text = text\n          .replaceAll(RegExp(r'customer\\s*list', caseSensitive: false), '')\n          .replaceAll(RegExp(r'discount\\s*list', caseSensitive: false), '')\n          .replaceAll(RegExp(r'customer\\s*discount', caseSensitive: false), '')\n          .replaceAll('고객 리스트', '')\n          .replaceAll('고객리스트', '')\n          .replaceAll('할인 고객 리스트', '')\n          .replaceAll('할인고객리스트', '')\n          .replaceAll('할인 고객', '')\n          .replaceAll('할인고객', '')\n          .replaceAll(RegExp(r'\\s+'), ' ')\n          .trim();\n      return text;\n    }\n\n    bool isGeneric(String raw) {\n      final key = raw\n          .trim()\n          .toLowerCase()\n          .replaceAll(RegExp(r'[\\s_./()-]+'), '');\n      const generic = <String>{\n        '할인',\n        '할인율',\n        '할인금액',\n        '할인액',\n        'discount',\n        'discountrate',\n        'discountamount',\n        'name',\n        'customer',\n        'customername',\n        'phone',\n        'tel',\n        '연락처',\n        '전화번호',\n        '이름',\n        '성명',\n        '고객명',\n      };\n      return generic.contains(key);\n    }\n\n    bool looksLikeGroup(String raw) {\n      final v = raw.trim().toLowerCase();\n      if (v.isEmpty || isGeneric(v)) return false;\n      if (_isCustomerNameHeader(v) ||\n          _isDiscountHeader(v) ||\n          _isPhoneHeader(v)) {\n        return false;\n      }\n      return v.contains('라선협') ||\n          v.contains('지상사') ||\n          v.contains('협의회') ||\n          v.contains('회원사') ||\n          v.contains('법인장') ||\n          v.contains('지인') ||\n          v.contains('아파트') ||\n          v.contains('기업') ||\n          v.contains('특별') ||\n          v.contains('파트너') ||\n          v.contains('협력사') ||\n          v.contains('할인');\n    }\n\n    // Discount tables are side-by-side in Row data.\n    // Search only the current table's local band so a neighboring\n    // discount title can never be selected.\n    final minRow = headerRow - 12 < 0 ? 0 : headerRow - 12;\n    final startCol = customerColumn - 1 < 0 ? 0 : customerColumn - 1;\n\n    for (var rr = headerRow; rr >= minRow; rr--) {\n      final row = sheet[rr];\n      if (row.isEmpty) continue;\n      final endCol = customerColumn + 6 < row.length\n          ? customerColumn + 6\n          : row.length - 1;\n\n      for (var cc = startCol; cc <= endCol; cc++) {\n        final raw = row[cc].trim();\n        if (!looksLikeGroup(raw)) continue;\n        final cleaned = clean(raw);\n        if (cleaned.isNotEmpty && !isGeneric(cleaned)) {\n          return cleaned;\n        }\n      }\n    }\n\n    return '';\n  }\n\n"
s=s[:start]+helper+s[end:]
wr(p,s)

p=cwd/'lib/services/freight_service.dart'
s=rd(p)
old="  static bool _nameMatches(\n    String value,\n    Iterable<String> candidates,\n  ) {\n    final target =\n        value.trim().toLowerCase().replaceAll(RegExp(r'\\s+'), ' ');\n    if (target.isEmpty) return false;\n    return candidates.any(\n      (candidate) =>\n          candidate.trim().isNotEmpty &&\n          candidate\n                  .trim()\n                  .toLowerCase()\n                  .replaceAll(RegExp(r'\\s+'), ' ') ==\n              target,\n    );\n  }"
new="  static List<String> _nameTokens(String value) => value\n      .replaceAll(RegExp(r'[\\?\\*]+'), '/')\n      .split(RegExp(r'[/,;|()]+'))\n      .map((e) => e.trim().toLowerCase().replaceAll(RegExp(r'\\s+'), ' '))\n      .where((e) => e.isNotEmpty)\n      .toSet()\n      .toList(growable: false);\n\n  static int _nameMatchRank(String value, String candidate) {\n    final a = _nameTokens(value).toSet();\n    final b = _nameTokens(candidate).toSet();\n    if (a.isEmpty || b.isEmpty) return 9999;\n\n    final overlap = a.intersection(b);\n    if (overlap.isEmpty) return 9999;\n\n    if (a.length == b.length && a.containsAll(b) && b.containsAll(a)) {\n      return 0;\n    }\n    if (a.containsAll(b)) return 10 + (a.length - b.length);\n    if (b.containsAll(a)) return 30 - b.length.clamp(0, 20);\n    return 50 - overlap.length.clamp(0, 20);\n  }\n\n  static bool _nameMatches(\n    String value,\n    Iterable<String> candidates,\n  ) =>\n      candidates.any(\n        (candidate) =>\n            candidate.trim().isNotEmpty &&\n            _nameMatchRank(value, candidate) < 9999,\n      );"
if old not in s: raise SystemExit('FreightService _nameMatches anchor not found')
s=s.replace(old,new,1)
old="    Map<String, dynamic>? allRouteMatch;\n    for (final raw in rows) {\n      final row = Map<String, dynamic>.from(raw);\n      final ruleRoute = '${row['route_key'] ?? ''}'.trim();\n      if (ruleRoute != 'all' && ruleRoute != routeKey) continue;\n      if (!_phoneMatches(normalizedPhone, '${row['phone'] ?? ''}')) {\n        continue;\n      }\n      if (!_nameMatches(\n        name,\n        [\n          '${row['customer_name'] ?? ''}',\n          '${row['company_name'] ?? ''}',\n        ],\n      )) {\n        continue;\n      }\n      if (ruleRoute == routeKey) return row;\n      allRouteMatch ??= row;\n    }\n    return allRouteMatch;"
new="    Map<String, dynamic>? bestRouteMatch;\n    Map<String, dynamic>? bestAllMatch;\n    var bestRouteRank = 9999;\n    var bestAllRank = 9999;\n\n    for (final raw in rows) {\n      final row = Map<String, dynamic>.from(raw);\n      final ruleRoute = '${row['route_key'] ?? ''}'.trim();\n      if (ruleRoute != 'all' && ruleRoute != routeKey) continue;\n      if (!_phoneMatches(normalizedPhone, '${row['phone'] ?? ''}')) {\n        continue;\n      }\n\n      final candidates = [\n        '${row['customer_name'] ?? ''}',\n        '${row['company_name'] ?? ''}',\n      ];\n      var rank = 9999;\n      for (final candidate in candidates) {\n        if (candidate.trim().isEmpty) continue;\n        final candidateRank = _nameMatchRank(name, candidate);\n        if (candidateRank < rank) rank = candidateRank;\n      }\n      if (rank >= 9999) continue;\n\n      if (ruleRoute == routeKey) {\n        if (rank < bestRouteRank) {\n          bestRouteRank = rank;\n          bestRouteMatch = row;\n        }\n      } else if (rank < bestAllRank) {\n        bestAllRank = rank;\n        bestAllMatch = row;\n      }\n    }\n    return bestRouteMatch ?? bestAllMatch;"
if old not in s: raise SystemExit('FreightService fallback loop anchor not found')
s=s.replace(old,new,1)
wr(p,s)

p=cwd/'lib/screens/statement_preview_dialog.dart'
s=rd(p)
old="    final actualDiscountPercent = freight.lines\n        .map((line) => line.discountPercent)\n        .fold<double>(0, (best, value) => value > best ? value : best);\n    final actualDiscountPctText =\n        actualDiscountPercent > 0 ? '${pctText(actualDiscountPercent)}%' : '';"
new="    final actualDiscountPercent = freight.lines\n        .map((line) => line.discountPercent)\n        .fold<double>(0, (best, value) => value > best ? value : best);\n    final noteDiscountMatch = RegExp(r'([0-9]+(?:\\.[0-9]+)?)%\\s*적용')\n        .firstMatch(displayAutoNotes);\n    final noteDiscountPercent =\n        double.tryParse(noteDiscountMatch?.group(1) ?? '') ?? 0;\n    final actualDiscountPctText = actualDiscountPercent > 0\n        ? '${pctText(actualDiscountPercent)}%'\n        : (noteDiscountPercent > 0\n            ? '${noteDiscountPercent.toStringAsFixed(\n                (noteDiscountPercent - noteDiscountPercent.roundToDouble())\n                            .abs() <\n                        .001\n                    ? 0\n                    : 2,\n              )}%'\n            : '');"
if old not in s: raise SystemExit('statement percent anchor not found')
s=s.replace(old,new,1)
wr(p,s)
print('Patch180 applied.')