"""Generate the same upright side-view symbols and sea path for web and Flutter."""
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT / 'shared-route-map/geometry.json').read_text())
def svg_path(commands):
    return ' '.join(c[0] + ' '.join(map(str, c[1:])) for c in commands)
def dart_path(commands):
    methods = {'M': 'moveTo', 'L': 'lineTo', 'C': 'cubicTo', 'Z': 'close'}
    return 'Path()' + ''.join('..' + methods[c[0]] + '(' + ','.join(map(str, c[1:])) + ')' for c in commands)
def color(value):
    if value == 'none': return 'Color(0x00000000)'
    return 'Color(0xFF' + value[1:].upper() + ')'

icons = {key: ''.join('<path d="' + svg_path(p['commands']) + '" fill="' + p['fill'] + '" stroke="' + p['stroke'] + '" stroke-width="1.5" stroke-linejoin="round"/>' for p in paths) for key, paths in data['vehicles'].items()}
web = '// Generated from shared-route-map/geometry.json.\nconst routeSeaPath = ' + json.dumps(svg_path(data['sea'])) + ';\nconst routeVehicleViewBox = ' + json.dumps(data['viewBox']) + ';\nconst routeVehicleSvg = ' + json.dumps(icons) + ';\n'
dart = "// Generated by tool/generate_route_geometry.py.\nimport 'dart:ui';\n\nPath sharedSeaRoutePath() => " + dart_path(data['sea']) + ';\n\nvoid drawSharedRouteVehicle(Canvas canvas, String vehicle) {\n  switch (vehicle) {\n'
for key, paths in data['vehicles'].items():
    dart += "    case '" + key + "':\n"
    for i,p in enumerate(paths):
        dart += '      final p' + str(i) + ' = ' + dart_path(p['commands']) + ';\n'
        dart += '      canvas.drawPath(p' + str(i) + ', Paint()..color = const ' + color(p['fill']) + ');\n'
        dart += '      canvas.drawPath(p' + str(i) + ', Paint()..color = const ' + color(p['stroke']) + '..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);\n'
    dart += '      break;\n'
dart += '  }\n}\n'
targets = [('dist/route-geometry.js', web)] if (ROOT / 'dist').exists() else [('lib/core/route_map_geometry.dart', dart)]
for name, output in targets:
    target = ROOT / name
    if '--check' in sys.argv:
        if not target.exists() or target.read_text() != output:
            raise SystemExit('Stale route geometry: ' + name)
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(output)
