"""Generate deterministic Dart defaults from the shared web/app UI contract."""
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT / 'shared-ui-text/contract.json').read_text())

def dart(value):
    if isinstance(value, dict):
        return '{\n' + ',\n'.join(f'  {dart(k)}: {dart(v)}' for k, v in value.items()) + '\n}'
    return json.dumps(value, ensure_ascii=False).replace('$', '\\$')

output = '// Generated by tool/generate_shared_ui_text.py. Edit shared-ui-text/contract.json.\n'
for name, key, value_type in [('sharedTextAliases', 'aliases', 'String'), ('sharedAppTextKeys', 'appKeys', 'String'), ('sharedKoreanTextKeys', 'koreanKeys', 'String'), ('sharedTextDefaults', 'defaults', 'Map<String, String>')]:
    output += f'const {name} = <String, {value_type}>' + dart(data[key]) + ';\n'
target = ROOT / 'lib/core/shared_ui_text_catalog.dart'
if '--check' in sys.argv:
    if not target.exists() or target.read_text() != output:
        raise SystemExit('Shared UI text catalog is stale; run tool/generate_shared_ui_text.py')
else:
    target.write_text(output)
