// lib/core/app_language.dart

enum AppLanguage { korean, english, lao }

extension AppLanguageExt on AppLanguage {
  String get code {
    switch (this) {
      case AppLanguage.korean:
        return 'ko';
      case AppLanguage.english:
        return 'en';
      case AppLanguage.lao:
        return 'lo';
    }
  }

  String get flag {
    switch (this) {
      case AppLanguage.korean:
        return '🇰🇷';
      case AppLanguage.english:
        return '🇬🇧';
      case AppLanguage.lao:
        return '🇱🇦';
    }
  }

  String get label {
    switch (this) {
      case AppLanguage.korean:
        return '한국어';
      case AppLanguage.english:
        return 'English';
      case AppLanguage.lao:
        return 'ລາວ';
    }
  }

  /// Phetsarath OT is used only while Lao is selected. Korean/English retain
  /// the existing NotoSansKR theme, so the visual layout does not change.
  String? get fontFamily => this == AppLanguage.lao ? 'PhetsarathOT' : null;

  String get flagLabel => '$flag $label';
}

class AppStrings {
  AppStrings._();

  static const Map<AppLanguage, Map<String, String>> values = {
    AppLanguage.korean: {
      'home_title': 'LK Group',
      'tracking_title': '화물 조회',
      'quote_title': '운임 확인 및 견적 요청',
      'account_title': '계정',
      'cargo_management_title': '화물 관리',
      'management_menu_title': '관리 메뉴',
      'login_title': '사용자 로그인',
      'home': '홈',
      'tracking': '화물 조회',
      'quote': '운임 확인',
      'account': '계정',
      'cargo_management': '화물 관리',
      'management_menu': '관리 메뉴',
      'chip_quote': '운임 견적',
      'notifications': '알림',
      'no_notifications': '새 알림이 없습니다.',
      'close': '닫기',
      'confirm': '확인',
      'schedule': '선적 일정',
      'notice': '공지 및 안내',
      'list_manage': '목록 관리',
      'list_details': '목록 자세히 보기',
      'contact': '상담 및 연락처',
      'consult_open': '상담하기',
      'consult_close': '상담 닫기',
      'ai_consult': 'AI 상담',
      'ai_description': '운송 일정·운임·화물 조회·통관에 대한 일반 안내를 도와드립니다.',
      'question_hint': '질문을 입력하세요...',
      'consult_start': '상담 시작',
      'question_required': '질문을 입력해 주세요.',
      'consult_failed': 'AI 상담을 연결하지 못했습니다.',
      'staff_confirmation': '정확한 일정·운임·통관 정보는 담당자 확인이 필요합니다.',
      'notice_title': '공지사항',
      'notice_load_failed': '공지사항 조회 실패',
      'no_notice': '등록된 공지사항이 없습니다.',
      'schedule_load_failed': '선적 일정 조회 실패',
      'no_schedule': '등록된 선적 일정이 없습니다.',
      'booking_close': '접수 마감',
      'arrival_expected': '도착 예정',
      'translation_failed': '번역을 적용하지 못해 원문을 표시합니다.',
      'all': '전체',
      'route': '운송 경로',
      'year': '년도',
      'voyage': '항차',
      'invoice_number': '송장번호',
      'recipient_name': '이름/라오스 수령인',
      'cargo_search': '화물 검색',
      'no_results': '검색 결과가 없습니다.',
      'login_required': '로그인 후 이용할 수 있습니다.',
      'login': '로그인 하기',
      'freight_check': '운임 확인',
      'box_information': '박스 정보 입력',
      'moving_goods': '이삿짐',
      'select_all_boxes': '전체 박스 선택',
      'add_box': '박스 추가',
      'box': '박스',
      'extra_cost': '기타 비용 추가',
      'discount': '할인',
      'delete': '삭제',
      'view_quote': '견적서 보기',
      'quote_history': '견적 요청 내역',
      'bulk_quote': '대량 혹은 특수 견적 요청',
      'box_packing': '박스 포장',
      'weight': '무게(kg)',
      'width': '가로(cm)',
      'length': '세로(cm)',
      'height': '높이(cm)',
      'quantity': '수량',
      'email_account': '계정',
      'password': '암호',
      'remember_account': '회원아이디 기억하기',
      'remember_password': '암호 기억하기',
      'sign_in': '접속',
      'sign_up': '회원가입',
      'sign_out': '로그아웃',
      'delete_account': '회원 탈퇴',
      'phone': '전화번호',
      'role': '권한',
      'company': '회사명',
      'address': '주소',
      'edit_profile': '회원 정보 변경',
      'change_password': '암호 변경',
      'not_registered': '등록되지 않음',
      'camera': '카메라',
      'select_photo': '사진 선택',
    },
    AppLanguage.english: {
      'home_title': 'LK Group',
      'tracking_title': 'Cargo Tracking',
      'quote_title': 'Freight Check & Quote Request',
      'account_title': 'Account',
      'cargo_management_title': 'Cargo Management',
      'management_menu_title': 'Management',
      'login_title': 'User Login',
      'home': 'Home',
      'tracking': 'Tracking',
      'quote': 'Freight',
      'account': 'Account',
      'cargo_management': 'Cargo',
      'management_menu': 'Management',
      'chip_quote': 'Quote',
      'notifications': 'Notifications',
      'no_notifications': 'There are no new notifications.',
      'close': 'Close',
      'confirm': 'OK',
      'schedule': 'Shipping Schedule',
      'notice': 'Notices & Information',
      'list_manage': 'Manage List',
      'list_details': 'View All',
      'contact': 'Contact & Consultation',
      'consult_open': 'Ask Us',
      'consult_close': 'Close Consultation',
      'ai_consult': 'AI Consultation',
      'ai_description': 'Ask for general guidance about schedules, freight, cargo tracking and customs.',
      'question_hint': 'Enter your question...',
      'consult_start': 'Ask AI',
      'question_required': 'Please enter a question.',
      'consult_failed': 'The AI consultation could not be reached.',
      'staff_confirmation': 'Exact schedules, rates and customs details require staff confirmation.',
      'notice_title': 'Notices',
      'notice_load_failed': 'Could not load notices',
      'no_notice': 'There are no notices.',
      'schedule_load_failed': 'Could not load the shipping schedule',
      'no_schedule': 'There are no shipping schedules.',
      'booking_close': 'Booking closes',
      'arrival_expected': 'Expected arrival',
      'translation_failed': 'Translation is unavailable, so the original text is shown.',
      'all': 'All',
      'route': 'Route',
      'year': 'Year',
      'voyage': 'Voyage',
      'invoice_number': 'Invoice Number',
      'recipient_name': 'Name / Laos Recipient',
      'cargo_search': 'Search Cargo',
      'no_results': 'No results found.',
      'login_required': 'Please log in to continue.',
      'login': 'Log In',
      'freight_check': 'Check Freight',
      'box_information': 'Box Information',
      'moving_goods': 'Moving Goods',
      'select_all_boxes': 'Select All Boxes',
      'add_box': 'Add Box',
      'box': 'Box',
      'extra_cost': 'Add Extra Cost',
      'discount': 'Discount',
      'delete': 'Delete',
      'view_quote': 'View Quote',
      'quote_history': 'Quote Requests',
      'bulk_quote': 'Bulk or Special Quote',
      'box_packing': 'Box Packing',
      'weight': 'Weight (kg)',
      'width': 'Width (cm)',
      'length': 'Length (cm)',
      'height': 'Height (cm)',
      'quantity': 'Quantity',
      'email_account': 'Email / Account',
      'password': 'Password',
      'remember_account': 'Remember Account',
      'remember_password': 'Remember Password',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'sign_out': 'Sign Out',
      'delete_account': 'Delete Account',
      'phone': 'Phone',
      'role': 'Role',
      'company': 'Company',
      'address': 'Address',
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'not_registered': 'Not registered',
      'camera': 'Camera',
      'select_photo': 'Select Photo',
    },
    AppLanguage.lao: {
      'home_title': 'LK Group',
      'tracking_title': 'ຕິດຕາມສິນຄ້າ',
      'quote_title': 'ກວດສອບຄ່າຂົນສົ່ງ ແລະ ຂໍໃບສະເໜີລາຄາ',
      'account_title': 'ບັນຊີ',
      'cargo_management_title': 'ຈັດການສິນຄ້າ',
      'management_menu_title': 'ເມນູຈັດການ',
      'login_title': 'ເຂົ້າລະບົບ',
      'home': 'ໜ້າຫຼັກ',
      'tracking': 'ຕິດຕາມ',
      'quote': 'ຄ່າຂົນສົ່ງ',
      'account': 'ບັນຊີ',
      'cargo_management': 'ສິນຄ້າ',
      'management_menu': 'ຈັດການ',
      'chip_quote': 'ໃບສະເໜີລາຄາ',
      'notifications': 'ແຈ້ງເຕືອນ',
      'no_notifications': 'ບໍ່ມີແຈ້ງເຕືອນໃໝ່.',
      'close': 'ປິດ',
      'confirm': 'ຕົກລົງ',
      'schedule': 'ຕາຕະລາງການຂົນສົ່ງ',
      'notice': 'ແຈ້ງການ ແລະ ຂໍ້ມູນ',
      'list_manage': 'ຈັດການລາຍການ',
      'list_details': 'ເບິ່ງທັງໝົດ',
      'contact': 'ຕິດຕໍ່ ແລະ ປຶກສາ',
      'consult_open': 'ສອບຖາມ',
      'consult_close': 'ປິດການປຶກສາ',
      'ai_consult': 'ປຶກສາ AI',
      'ai_description': 'ສອບຖາມຂໍ້ມູນທົ່ວໄປກ່ຽວກັບກຳນົດການ, ຄ່າຂົນສົ່ງ, ການຕິດຕາມ ແລະ ພາສີ.',
      'question_hint': 'ພິມຄຳຖາມ...',
      'consult_start': 'ສອບຖາມ AI',
      'question_required': 'ກະລຸນາພິມຄຳຖາມ.',
      'consult_failed': 'ບໍ່ສາມາດເຊື່ອມຕໍ່ການປຶກສາ AI ໄດ້.',
      'staff_confirmation': 'ຕ້ອງໃຫ້ພະນັກງານຢືນຢັນກຳນົດການ, ລາຄາ ແລະ ຂໍ້ມູນພາສີທີ່ແນ່ນອນ.',
      'notice_title': 'ແຈ້ງການ',
      'notice_load_failed': 'ໂຫຼດແຈ້ງການບໍ່ສຳເລັດ',
      'no_notice': 'ຍັງບໍ່ມີແຈ້ງການ.',
      'schedule_load_failed': 'ໂຫຼດຕາຕະລາງບໍ່ສຳເລັດ',
      'no_schedule': 'ຍັງບໍ່ມີຕາຕະລາງການຂົນສົ່ງ.',
      'booking_close': 'ປິດຮັບຈອງ',
      'arrival_expected': 'ຄາດວ່າຈະຮອດ',
      'translation_failed': 'ບໍ່ສາມາດແປພາສາໄດ້, ຈຶ່ງສະແດງຂໍ້ຄວາມຕົ້ນສະບັບ.',
      'all': 'ທັງໝົດ',
      'route': 'ເສັ້ນທາງ',
      'year': 'ປີ',
      'voyage': 'ຖ້ຽວ',
      'invoice_number': 'ເລກທີໃບຂົນສົ່ງ',
      'recipient_name': 'ຊື່ / ຜູ້ຮັບໃນລາວ',
      'cargo_search': 'ຄົ້ນຫາສິນຄ້າ',
      'no_results': 'ບໍ່ພົບຜົນການຄົ້ນຫາ.',
      'login_required': 'ກະລຸນາເຂົ້າລະບົບເພື່ອສືບຕໍ່.',
      'login': 'ເຂົ້າລະບົບ',
      'freight_check': 'ກວດສອບຄ່າຂົນສົ່ງ',
      'box_information': 'ຂໍ້ມູນກ່ອງ',
      'moving_goods': 'ເຄື່ອງຍ້າຍເຮືອນ',
      'select_all_boxes': 'ເລືອກທຸກກ່ອງ',
      'add_box': 'ເພີ່ມກ່ອງ',
      'box': 'ກ່ອງ',
      'extra_cost': 'ເພີ່ມຄ່າໃຊ້ຈ່າຍ',
      'discount': 'ສ່ວນລົດ',
      'delete': 'ລົບ',
      'view_quote': 'ເບິ່ງໃບສະເໜີລາຄາ',
      'quote_history': 'ຄຳຂໍໃບສະເໜີລາຄາ',
      'bulk_quote': 'ຂໍລາຄາສິນຄ້າຈຳນວນຫຼາຍ/ພິເສດ',
      'box_packing': 'ບັນຈຸກ່ອງ',
      'weight': 'ນ້ຳໜັກ (kg)',
      'width': 'ກວ້າງ (cm)',
      'length': 'ຍາວ (cm)',
      'height': 'ສູງ (cm)',
      'quantity': 'ຈຳນວນ',
      'email_account': 'ອີເມວ / ບັນຊີ',
      'password': 'ລະຫັດຜ່ານ',
      'remember_account': 'ຈື່ບັນຊີ',
      'remember_password': 'ຈື່ລະຫັດຜ່ານ',
      'sign_in': 'ເຂົ້າລະບົບ',
      'sign_up': 'ລົງທະບຽນ',
      'sign_out': 'ອອກຈາກລະບົບ',
      'delete_account': 'ລົບບັນຊີ',
      'phone': 'ເບີໂທ',
      'role': 'ສິດທິ',
      'company': 'ບໍລິສັດ',
      'address': 'ທີ່ຢູ່',
      'edit_profile': 'ແກ້ໄຂໂປຣໄຟລ໌',
      'change_password': 'ປ່ຽນລະຫັດຜ່ານ',
      'not_registered': 'ຍັງບໍ່ໄດ້ລົງທະບຽນ',
      'camera': 'ກ້ອງ',
      'select_photo': 'ເລືອກຮູບ',
    },
  };

  static String get(AppLanguage language, String key) =>
      values[language]?[key] ?? values[AppLanguage.korean]?[key] ?? key;
}
