import 'app_language.dart';
import '../services/shared_ui_text_service.dart';

String domesticText(AppLanguage language, String key) =>
    SharedUiTextService.instance.text('domestic.$key', language.code,
      (domesticWords[key] ?? domesticWords['REQUEST_FAILED']!)[language.index]);

const domesticWords = <String, List<String>>{
  "INVALID_BATCH": ["송장번호는 한 번에 1~50개까지 등록할 수 있습니다.", "Register 1–50 tracking numbers at a time.", "ລົງທະບຽນໄດ້ 1–50 ເລກຕໍ່ຄັ້ງ."],

  "TOO_MANY_PHOTOS": ["기존 사진을 포함해 송장당 최대 50장까지 등록할 수 있습니다.", "Each waybill can have up to 50 photos, including existing photos.", "ແຕ່ລະໃບສົ່ງມີໄດ້ສູງສຸດ 50 ຮູບ ລວມຮູບເກົ່າ."],

  "recipientMasked": ["다른 고객의 이름과 연락처는 일부만 표시됩니다.", "Another customer's name and phone are partially masked.", "ຊື່ ແລະ ເບີໂທຂອງລູກຄ້າອື່ນຖືກປິດບັງບາງສ່ວນ."],

  "autoRefreshHint": ["등록·조회 시 배송 이력을 자동 확인합니다. 화면을 열어 둔 동안 5분마다 갱신합니다.", "History is checked automatically when saving or viewing, and every 5 minutes while this screen is open.", "ກວດປະຫວັດອັດຕະໂນມັດເມື່ອບັນທຶກ ຫຼື ເບິ່ງ ແລະ ທຸກ 5 ນາທີຂະນະເປີດໜ້ານີ້."],

  "photoHelp": ["선택한 사진은 이번에 등록하는 송장들에 함께 연결되며, 명세서 안에서 확인할 수 있습니다. JPG·PNG·WebP를 선택하세요.", "Selected photos are shared by the waybills saved together and shown inside the statement. Choose JPG, PNG or WebP.", "ຮູບຈະເຊື່ອມກັບໃບສົ່ງທີ່ບັນທຶກພ້ອມກັນ ແລະ ສະແດງໃນໃບລາຍການ. ໃຊ້ JPG, PNG ຫຼື WebP."],

  "waybillCount": ["연결 송장", "Linked waybills", "ໃບສົ່ງທີ່ເຊື່ອມ"],

  "removePhoto": ["선택 사진 제외", "Remove selected photo", "ເອົາຮູບທີ່ເລືອກອອກ"],

  "removeWaybill": ["송장번호 삭제", "Remove tracking number", "ລຶບເລກໃບສົ່ງ"],

  "addWaybill": ["송장번호 추가", "Add tracking number", "ເພີ່ມເລກໃບສົ່ງ"],

  "linkMethod": ["연결 방식", "Link method", "ວິທີເຊື່ອມ"],
  "linkStatement": ["LK 명세서 연결", "Link an LK statement", "ເຊື່ອມໃບລາຍການ LK"],
  "linkReference": ["별도 명세서·관리번호 연결", "Link a separate reference", "ເຊື່ອມເລກອ້າງອີງແຍກ"],
  "linkCargo": ["개별 화물 연결", "Link individual cargo", "ເຊື່ອມສິນຄ້າແຕ່ລະລາຍການ"],
  "linkLegacy": ["기존 송장만 등록된 배송", "Existing delivery without a reference", "ການຈັດສົ່ງເກົ່າທີ່ບໍ່ມີເລກອ້າງອີງ"],
  "stepStatement": ["1. 연결할 LK 명세서 또는 관리번호", "1. LK statement or reference to link", "1. ໃບລາຍການ LK ຫຼື ເລກອ້າງອີງ"],
  "stepWaybill": ["2. 라오스 배송업체 송장", "2. Lao carrier waybill", "2. ໃບສົ່ງຂອງບໍລິສັດຂົນສົ່ງລາວ"],
  "statementNumber": ["LK 명세서 번호", "LK statement number", "ເລກໃບລາຍການ LK"],
  "exampleStatement": ["예: LKS 03", "Example: LKS 03", "ຕົວຢ່າງ: LKS 03"],
  "confirmStatement": ["명세서 확인", "Confirm statement", "ກວດໃບລາຍການ"],
  "statementConfirmed": ["연결할 명세서 확인 완료", "Statement confirmed for linking", "ຢືນຢັນໃບລາຍການທີ່ຈະເຊື່ອມແລ້ວ"],
  "mappingHelp": ["경로·연도·항차를 선택하고 LK 명세서 번호를 확인하세요. 선택한 명세서 전체에 배송 송장을 연결합니다.", "Choose the route, year and voyage, then confirm the LK statement number. The waybill will link to the whole statement.", "ເລືອກເສັ້ນທາງ, ປີ ແລະ ຖ້ຽວ ແລ້ວກວດເລກໃບລາຍການ LK. ໃບສົ່ງຈະເຊື່ອມກັບໃບລາຍການທັງໝົດ."],
  "referenceType": ["관리번호 구분", "Reference type", "ປະເພດເລກອ້າງອີງ"],
  "referenceNumber": ["별도 명세서·관리번호", "Separate statement / reference number", "ເລກໃບລາຍການ / ອ້າງອີງແຍກ"],
  "local": ["별도 국내배송", "Separate domestic delivery", "ການຈັດສົ່ງພາຍໃນແຍກ"],
  "referenceHelp": ["전자상거래 또는 별도 국내배송에 사용하는 LK 관리번호를 입력하세요. 배송업체 송장번호는 아래에 따로 입력합니다.", "Enter the LK reference used for e-commerce or separate domestic deliveries. Enter the carrier tracking number separately below.", "ປ້ອນເລກອ້າງອີງ LK ສຳລັບອີຄອມເມີຊ ຫຼື ການຈັດສົ່ງພາຍໃນແຍກ. ປ້ອນເລກໃບສົ່ງຂອງຂົນສົ່ງຢູ່ດ້ານລຸ່ມ."],
  "waybillHelp": ["같은 명세서의 송장번호를 + 버튼으로 추가하세요. 번호별 배송업체를 선택하고 함께 저장합니다.", "Use + to add waybills for this statement. Select a carrier for each number and save together.", "ໃຊ້ປຸ່ມ + ເພີ່ມໃບສົ່ງໃນໃບລາຍການດຽວກັນ. ເລືອກຂົນສົ່ງແຕ່ລະເລກ ແລ້ວບັນທຶກພ້ອມກັນ."],
  "carrierHint": ["번호 형식에 따른 참고 추천입니다. 송장에 적힌 배송업체를 확인해 선택하세요.", "Suggestions use the number format only. Confirm the carrier printed on the waybill.", "ຄຳແນະນຳອີງຕາມຮູບແບບເລກເທົ່ານັ້ນ. ກວດບໍລິສັດທີ່ຢູ່ໃນໃບສົ່ງ."],
  "correctionHelp": ["업체나 송장번호를 정정하면 이전 배송사 이력은 초기화됩니다. 직접 등록한 이력과 사진은 유지됩니다.", "Correcting the carrier or number resets carrier events. Manually recorded events and photos are retained.", "ການແກ້ບໍລິສັດ ຫຼື ເລກໃບສົ່ງຈະລ້າງປະຫວັດຈາກຂົນສົ່ງ. ປະຫວັດທີ່ບັນທຶກເອງ ແລະ ຮູບຍັງຢູ່."],
  "lookupKind": ["조회 기준", "Search by", "ຄົ້ນຫາຕາມ"],
  "STATEMENT_REQUIRED": ["경로·연도·항차와 명세서 번호를 입력한 뒤 명세서 확인을 눌러 주세요.", "Choose the route, year and voyage, enter the number, then confirm the statement.", "ເລືອກເສັ້ນທາງ, ປີ, ຖ້ຽວ ແລະ ປ້ອນເລກ ແລ້ວກວດໃບລາຍການ."],
  "STATEMENT_NOT_FOUND": ["선택한 경로·연도·항차에서 명세서를 찾지 못했습니다.", "No statement matches the selected route, year and voyage.", "ບໍ່ພົບໃບລາຍການໃນເສັ້ນທາງ, ປີ ແລະ ຖ້ຽວທີ່ເລືອກ."],
  "AMBIGUOUS_STATEMENT": ["같은 번호가 여러 명세서에 있습니다. LKS 03처럼 전체 명세서 번호를 입력하세요.", "More than one statement matches. Enter the full statement number, such as LKS 03.", "ພົບຫຼາຍໃບລາຍການ. ປ້ອນເລກຄົບ ເຊັ່ນ LKS 03."],
  "INVALID_REFERENCE": ["관리번호 구분과 전체 번호를 확인하세요. 영문·숫자·점·하이픈·밑줄·슬래시를 사용할 수 있습니다.", "Check the reference type and full number. Use letters, digits, dots, hyphens, underscores or slashes.", "ກວດປະເພດ ແລະ ເລກອ້າງອີງ. ໃຊ້ອັກສອນອັງກິດ, ຕົວເລກ, ຈຸດ, ຂີດ ຫຼື ເຄື່ອງໝາຍທັບ."],
  "INVALID_LINK_SCOPE": ["연결 방식을 확인하세요.", "Check the link method.", "ກວດວິທີເຊື່ອມ."],
  "cargoCount": ["포함 화물", "Cargo items", "ລາຍການສິນຄ້າ"],

  "filtersLoading": ["검색 조건을 불러오는 중…", "Loading search filters…", "ກຳລັງໂຫຼດເງື່ອນໄຂຄົ້ນຫາ…"],
  "filtersFailed": ["검색 조건을 불러오지 못했습니다. 다시 시도하거나 번호만으로 조회하세요.", "Filters could not be loaded. Retry or search by number only.", "ໂຫຼດເງື່ອນໄຂບໍ່ໄດ້. ລອງໃໝ່ ຫຼື ຄົ້ນຫາດ້ວຍເລກເທົ່ານັ້ນ."],
  "filtersEmpty": ["선택할 운송 데이터가 없습니다. 번호만으로 조회할 수 있습니다.", "No shipment filters are available. You can search by number only.", "ບໍ່ມີຂໍ້ມູນຂົນສົ່ງໃຫ້ເລືອກ. ຄົ້ນຫາດ້ວຍເລກໄດ້."],
  "retry": ["다시 시도", "Retry", "ລອງໃໝ່"],
  "status": ["배송 상태", "Delivery status", "ສະຖານະຈັດສົ່ງ"],
  "title": [
    "라오스 국내 배송 조회 & 관리 (e-commerce)",
    "Laos Domestic Delivery Tracking & Management (e-commerce)",
    "ການຕິດຕາມແລະຈັດການການຂົນສົ່ງໃນປະເທດລາວ (e-commerce)",
  ],
  "publicTitle": ["라오스 국내 배송 조회 (e-commerce)", "Laos Domestic Delivery Tracking (e-commerce)", "ການຕິດຕາມການຂົນສົ່ງໃນປະເທດລາວ (e-commerce)"],
  "manage": ["라오스 국내 배송 조회 & 관리 (e-commerce)", "Laos Domestic Delivery Tracking & Management (e-commerce)", "ການຕິດຕາມແລະຈັດການການຂົນສົ່ງໃນປະເທດລາວ (e-commerce)"],
  "carrier": ["배송업체", "Carrier", "ບໍລິສັດຂົນສົ່ງ"],
  "tracking": [
    "국내배송 송장번호 전체",
    "Full domestic tracking number",
    "ເລກໃບສົ່ງພາຍໃນຄົບຖ້ວນ",
  ],
  "all": ["업체 전체", "All carriers", "ທຸກບໍລິສັດ"],
  "any": ["전체", "All", "ທັງໝົດ"],
  "statement": ["명세서 번호 / 화물번호", "Statement / cargo number", "ເລກໃບລາຍການ / ເລກສິນຄ້າ"],
  "route": ["운송경로", "Transport route", "ເສັ້ນທາງ"],
  "year": ["연도", "Year", "ປີ"],
  "voyage": ["항차", "Voyage", "ຖ້ຽວຂົນສົ່ງ"],
  "selectCargo": ["명세서·화물 선택", "Select statement / cargo", "ເລືອກໃບລາຍການ / ສິນຄ້າ"],
  "selectCarrier": ["배송업체를 확인해 선택하세요", "Confirm and select the carrier", "ກວດ ແລະ ເລືອກບໍລິສັດ"],
  "detectHint": ["번호 형식에 따라 업체를 자동 선택합니다. 직접 변경할 수 있습니다.", "Recognized number formats select a carrier. You can change it.", "ເລືອກບໍລິສັດຕາມຮູບແບບເລກ. ທ່ານປ່ຽນໄດ້."],
  "ansCandidate": ["ANS 번호 형식과 유사합니다. 송장 사진을 확인한 후 업체를 선택하세요.", "This resembles an ANS number. Check the waybill photo before selecting the carrier.", "ຮູບແບບຄ້າຍເລກ ANS. ກວດຮູບໃບສົ່ງກ່ອນເລືອກ."],
  "noLinked": ["화물은 확인됐지만 연결된 국내배송 송장이 아직 없습니다.", "Cargo found; no domestic waybill has been linked yet.", "ພົບສິນຄ້າ ແຕ່ຍັງບໍ່ມີໃບສົ່ງທີ່ເຊື່ອມ."],
  "INVALID_STATEMENT": ["명세서 번호 또는 화물번호 전체를 입력하세요.", "Enter the complete statement or cargo number.", "ປ້ອນເລກໃບລາຍການ ຫຼື ສິນຄ້າຄົບຖ້ວນ."],
  "INVALID_YEAR": ["연도를 확인해 주세요.", "Check the year.", "ກວດປີ."],
  "NARROW_SEARCH": ["운송경로와 연도를 선택해 검색 범위를 좁혀 주세요.", "Select a route and year to narrow your search.", "ເລືອກເສັ້ນທາງ ແລະ ປີເພື່ອຈຳກັດການຄົ້ນຫາ."],
  "CARGO_REQUIRED": ["연결할 명세서·화물을 먼저 선택하세요.", "Select the statement / cargo first.", "ເລືອກໃບລາຍການ / ສິນຄ້າກ່ອນ."],
  "search": ["검색", "Search", "ຄົ້ນຫາ"],
  "add": ["송장 등록", "Register waybill", "ລົງທະບຽນໃບສົ່ງ"],
  "list": ["등록된 송장", "Registered waybills", "ໃບສົ່ງທີ່ລົງທະບຽນ"],
  "hint": [
    "명세서 번호를 입력하면 연결된 배송 내역을 한 번에 확인할 수 있습니다. 필요하면 경로·연도·항차를 선택하세요.",
    "Enter your statement number to see linked deliveries. Select a route, year or voyage if needed.",
    "ປ້ອນເລກໃບລາຍການເພື່ອເບິ່ງການຈັດສົ່ງ. ເລືອກເສັ້ນທາງ, ປີ ຫຼື ຖ້ຽວຖ້າຕ້ອງການ.",
  ],
  "manageHint": ["LK 명세서별로 배송업체 송장과 사진, 배송 이력을 관리합니다.", "Manage carrier waybills, photos and delivery history by LK statement.", "ຈັດການໃບສົ່ງ, ຮູບ ແລະ ປະຫວັດຕາມໃບລາຍການ LK."],
  "loading": [
    "배송 이력을 확인하고 있습니다…",
    "Checking delivery history…",
    "ກຳລັງກວດປະຫວັດການຈັດສົ່ງ…",
  ],
  "empty": [
    "조회 가능한 배송 내역이 없습니다. 입력한 번호와 검색 조건을 확인해 주세요.",
    "No delivery records found. Check the number and search filters.",
    "ບໍ່ພົບການຈັດສົ່ງ. ກວດເລກ ແລະ ເງື່ອນໄຂຄົ້ນຫາ.",
  ],
  "city": ["시내", "City", "ໃນເມືອງ"],
  "province": ["지방", "Province", "ຕ່າງແຂວງ"],
  "domestic": ["국내배송", "Domestic", "ພາຍໃນ"],
  "inbound": ["라오스 입국 연계", "Inbound", "ຂາເຂົ້າ"],
  "outbound": ["라오스 출국 연계", "Outbound", "ຂາອອກ"],
  "ecommerce": ["전자상거래", "E-commerce", "ອີຄອມເມີຊ"],
  "express": ["특송", "Express", "ດ່ວນ"],
  "kind": ["배송 구분", "Delivery type", "ປະເພດຈັດສົ່ງ"],
  "service": ["운송 구분", "Service", "ປະເພດບໍລິການ"],
  "photo": ["등록된 송장 사진", "Waybill photo", "ຮູບໃບສົ່ງ"],
  "photoInput": ["송장 사진 여러 장 선택 · 최대 50장, 장당 5MB, 합계 250MB", "Select waybill photos · up to 50, 5MB each, 250MB total", "ເລືອກຫຼາຍຮູບ · ສູງສຸດ 50 ຮູບ, ຮູບລະ 5MB, ລວມ 250MB"],
  "noPhoto": [
    "등록된 송장 사진이 없습니다.",
    "No waybill photo registered.",
    "ຍັງບໍ່ມີຮູບໃບສົ່ງ.",
  ],
  "restricted": [
    "송장 사진은 해당 고객과 담당자만 볼 수 있습니다.",
    "The waybill photo is available to the recipient and authorized staff.",
    "ຮູບໃບສົ່ງສຳລັບຜູ້ຮັບ ແລະ ຜູ້ມີສິດ.",
  ],
  "history": ["배송 이력", "Delivery history", "ປະຫວັດການຈັດສົ່ງ"],
  "timezone": ["라오스 시간 · UTC+7", "Laos time · UTC+7", "ເວລາລາວ · UTC+7"],
  "checked": ["최근 조회", "Last checked", "ກວດລ່າສຸດ"],
  "synced": ["배송사 확인", "Carrier data updated", "ອັບເດດຈາກຂົນສົ່ງ"],
  "official": ["배송사 사이트에서 확인", "Open carrier website", "ເບິ່ງເວັບຂົນສົ່ງ"],
  "refresh": ["배송 이력 조회", "Check delivery history", "ກວດປະຫວັດຈັດສົ່ງ"],
  "noEvents": [
    "아직 확인된 배송 이력이 없습니다.",
    "No delivery events confirmed yet.",
    "ຍັງບໍ່ມີປະຫວັດທີ່ຢືນຢັນ.",
  ],
  "staff": ["직원 기록", "Staff entry", "ພະນັກງານບັນທຶກ"],
  "carrierSource": ["배송사 기록", "Carrier entry", "ບໍລິສັດບັນທຶກ"],
  "manual": ["배송 이력 추가", "Add delivery event", "ເພີ່ມປະຫວັດ"],
  "when": ["처리 일시 (라오스 시간)", "Event date/time (Laos)", "ວັນເວລາ (ເວລາລາວ)"],
  "location": ["처리 지점 / 위치", "Branch / location", "ສາຂາ / ສະຖານທີ່"],
  "description": ["처리 내용", "Event details", "ລາຍລະອຽດ"],
  "cargo": [
    "연결할 명세서·화물",
    "Linked statement / cargo",
    "ໃບລາຍການ / ສິນຄ້າທີ່ເຊື່ອມ",
  ],
  "cargoSearch": ["명세서 번호 또는 화물번호로 검색", "Find by statement or cargo number", "ຄົ້ນດ້ວຍເລກໃບລາຍການ ຫຼື ສິນຄ້າ"],
  "unlinked": ["별도 국내배송", "Standalone domestic delivery", "ການຈັດສົ່ງແຍກ"],
  "receiver": ["수취인 이름", "Recipient name", "ຊື່ຜູ້ຮັບ"],
  "phone": ["수취인 전화번호", "Recipient phone", "ເບີໂທຜູ້ຮັບ"],
  "save": ["저장", "Save", "ບັນທຶກ"],
  "edit": ["수정", "Edit", "ແກ້ໄຂ"],
  "saved": ["송장을 저장했습니다.", "Waybill saved.", "ບັນທຶກໃບສົ່ງແລ້ວ."],
  "more": ["다음 페이지", "Next page", "ໜ້າຕໍ່ໄປ"],
  "prev": ["이전 페이지", "Previous page", "ໜ້າກ່ອນ"],
  "registered": ["송장 등록", "Registered", "ລົງທະບຽນ"],
  "accepted": ["접수", "Accepted", "ຮັບແລ້ວ"],
  "in_transit": ["이동 중", "In transit", "ກຳລັງຂົນສົ່ງ"],
  "ready_for_pickup": [
    "도착 · 수령 대기",
    "Ready for collection",
    "ຮອດແລ້ວ · ລໍຖ້າຮັບ",
  ],
  "out_for_delivery": ["배송 중", "Out for delivery", "ກຳລັງຈັດສົ່ງ"],
  "delivered": ["배송 완료", "Delivered", "ຈັດສົ່ງສຳເລັດ"],
  "returned": ["반송", "Returned", "ສົ່ງຄືນ"],
  "exception": ["확인 필요", "Needs attention", "ຕ້ອງກວດສອບ"],
  "unknown": ["상태 확인 필요", "Status unconfirmed", "ລໍຖ້າຢືນຢັນ"],
  "verify": [
    "배송사 인증이 필요합니다. 배송사 사이트에서 확인하거나 담당자가 이력을 등록할 수 있습니다.",
    "Carrier verification is required. Open the carrier website or ask staff to record an update.",
    "ຕ້ອງຢືນຢັນໃນເວັບຂົນສົ່ງ ຫຼື ໃຫ້ພະນັກງານບັນທຶກ.",
  ],
  "connection": [
    "배송사 자동 연동을 준비 중입니다. 현재 등록된 이력과 사진을 확인할 수 있습니다.",
    "Automatic carrier connection is pending. Registered events and photos remain available.",
    "ກຳລັງກຽມເຊື່ອມຕໍ່ຂົນສົ່ງ. ເບິ່ງປະຫວັດ ແລະ ຮູບທີ່ບັນທຶກໄດ້.",
  ],
  "failed": [
    "배송사의 최신 정보를 가져오지 못했습니다. 마지막으로 저장된 이력을 표시합니다.",
    "Latest carrier data is unavailable. Showing the last saved history.",
    "ດຶງຂໍ້ມູນໃໝ່ບໍ່ໄດ້. ສະແດງປະຫວັດທີ່ບັນທຶກລ່າສຸດ.",
  ],
  "INVALID_TRACKING": [
    "송장번호 전체를 확인해 주세요 (6~40자).",
    "Enter a complete tracking number (6–40 characters).",
    "ກວດເລກໃບສົ່ງ (6–40 ຕົວ).",
  ],
  "DUPLICATE_TRACKING": [
    "같은 업체·송장번호가 이미 등록되어 있습니다.",
    "This carrier and tracking number already exist.",
    "ເລກໃບສົ່ງນີ້ມີແລ້ວ.",
  ],
  "RECORD_CHANGED": [
    "다른 곳에서 변경되었습니다. 다시 조회 후 저장하세요.",
    "This record changed. Reload before saving.",
    "ຂໍ້ມູນປ່ຽນແລ້ວ. ໂຫຼດຄືນກ່ອນບັນທຶກ.",
  ],
  "FILE_TOO_LARGE": ["사진은 장당 5MB, 이번 선택 합계 15MB 이하여야 합니다.", "Photos must be at most 5MB each and 15MB total per selection.", "ຮູບຕ້ອງບໍ່ເກີນ 5MB ຕໍ່ຮູບ ແລະ ລວມ 15MB ຕໍ່ຄັ້ງ."],
  "INVALID_IMAGE": [
    "JPG, PNG, WebP 사진만 등록할 수 있습니다.",
    "Use a JPG, PNG or WebP photo.",
    "ໃຊ້ຮູບ JPG, PNG ຫຼື WebP.",
  ],
  "LOGIN_REQUIRED": [
    "로그인 후 조회할 수 있습니다.",
    "Sign in to track a parcel.",
    "ເຂົ້າລະບົບເພື່ອຕິດຕາມ.",
  ],
  "FORBIDDEN": [
    "등록·수정 권한이 없습니다.",
    "You do not have permission to edit.",
    "ບໍ່ມີສິດແກ້ໄຂ.",
  ],
  "TOO_MANY_REQUESTS": [
    "잠시 후 다시 조회해 주세요.",
    "Please wait a minute before trying again.",
    "ກະລຸນາລໍຖ້າໜຶ່ງນາທີ.",
  ],
  "REQUEST_FAILED": [
    "요청을 처리하지 못했습니다. 다시 시도해 주세요.",
    "The request failed. Please try again.",
    "ດຳເນີນການບໍ່ໄດ້. ລອງໃໝ່.",
  ],
};


