import 'app_language.dart';

String domesticText(AppLanguage language, String key) =>
    (domesticWords[key] ?? domesticWords['REQUEST_FAILED']!)[language.index];

const domesticWords = <String, List<String>>{
  "title": [
    "라오스 국내배송 조회",
    "Laos domestic tracking",
    "ຕິດຕາມການຈັດສົ່ງພາຍໃນລາວ",
  ],
  "manage": ["국내배송 송장 관리", "Domestic waybills", "ຈັດການໃບສົ່ງພາຍໃນ"],
  "carrier": ["배송업체", "Carrier", "ບໍລິສັດຂົນສົ່ງ"],
  "tracking": [
    "국내배송 송장번호 전체",
    "Full domestic tracking number",
    "ເລກໃບສົ່ງພາຍໃນຄົບຖ້ວນ",
  ],
  "all": ["업체 전체", "All carriers", "ທຸກບໍລິສັດ"],
  "search": ["검색", "Search", "ຄົ້ນຫາ"],
  "add": ["송장 등록", "Register waybill", "ລົງທະບຽນໃບສົ່ງ"],
  "list": ["등록된 송장", "Registered waybills", "ໃບສົ່ງທີ່ລົງທະບຽນ"],
  "hint": [
    "업체를 선택하고 송장번호 전체를 입력하세요.",
    "Choose a carrier and enter the full tracking number.",
    "ເລືອກບໍລິສັດ ແລະ ປ້ອນເລກໃບສົ່ງຄົບຖ້ວນ.",
  ],
  "loading": [
    "배송 이력을 확인하고 있습니다…",
    "Checking delivery history…",
    "ກຳລັງກວດປະຫວັດການຈັດສົ່ງ…",
  ],
  "empty": [
    "등록된 송장을 찾을 수 없습니다. 번호와 업체를 확인해 주세요.",
    "No registered waybill found. Check the number and carrier.",
    "ບໍ່ພົບໃບສົ່ງ. ກວດເລກ ແລະ ບໍລິສັດ.",
  ],
  "city": ["시내", "City", "ໃນເມືອງ"],
  "province": ["지방", "Province", "ຕ່າງແຂວງ"],
  "domestic": ["국내배송", "Domestic", "ພາຍໃນ"],
  "inbound": ["라오스 입국 연계", "Inbound", "ຂາເຂົ້າ"],
  "outbound": ["라오스 출국 연계", "Outbound", "ຂາອອກ"],
  "ecommerce": ["전자상거래", "E-commerce", "ອີຄອມເມີຊ"],
  "express": ["특송", "Express", "ດ່ວນ"],
  "kind": ["배송 구분", "Delivery type", "ປະເພດຈັດສົ່ງ"],
  "service": ["운송 구분", "Service", "ປະເພດບໍລິການ"],
  "photo": ["등록된 송장 사진", "Waybill photo", "ຮູບໃບສົ່ງ"],
  "photoInput": [
    "송장 사진 · JPG/PNG/WebP, 최대 5MB",
    "Waybill photo · JPG/PNG/WebP, max 5MB",
    "ຮູບໃບສົ່ງ · JPG/PNG/WebP, ສູງສຸດ 5MB",
  ],
  "noPhoto": [
    "등록된 송장 사진이 없습니다.",
    "No waybill photo registered.",
    "ຍັງບໍ່ມີຮູບໃບສົ່ງ.",
  ],
  "restricted": [
    "송장 사진은 해당 고객과 담당자만 볼 수 있습니다.",
    "The waybill photo is available to the recipient and authorized staff.",
    "ຮູບໃບສົ່ງສຳລັບຜູ້ຮັບ ແລະ ຜູ້ມີສິດ.",
  ],
  "history": ["배송 이력", "Delivery history", "ປະຫວັດການຈັດສົ່ງ"],
  "timezone": ["라오스 시간 · UTC+7", "Laos time · UTC+7", "ເວລາລາວ · UTC+7"],
  "checked": ["최근 조회", "Last checked", "ກວດລ່າສຸດ"],
  "synced": ["배송사 확인", "Carrier data updated", "ອັບເດດຈາກຂົນສົ່ງ"],
  "official": ["배송사 사이트에서 확인", "Open carrier website", "ເບິ່ງເວັບຂົນສົ່ງ"],
  "refresh": ["배송 이력 조회", "Check delivery history", "ກວດປະຫວັດຈັດສົ່ງ"],
  "noEvents": [
    "아직 확인된 배송 이력이 없습니다.",
    "No delivery events confirmed yet.",
    "ຍັງບໍ່ມີປະຫວັດທີ່ຢືນຢັນ.",
  ],
  "staff": ["직원 기록", "Staff entry", "ພະນັກງານບັນທຶກ"],
  "carrierSource": ["배송사 기록", "Carrier entry", "ບໍລິສັດບັນທຶກ"],
  "manual": ["배송 이력 추가", "Add delivery event", "ເພີ່ມປະຫວັດ"],
  "when": ["처리 일시 (라오스 시간)", "Event date/time (Laos)", "ວັນເວລາ (ເວລາລາວ)"],
  "location": ["처리 지점 / 위치", "Branch / location", "ສາຂາ / ສະຖານທີ່"],
  "description": ["처리 내용", "Event details", "ລາຍລະອຽດ"],
  "cargo": [
    "연결 화물 (선택)",
    "Linked cargo (optional)",
    "ສິນຄ້າທີ່ເຊື່ອມ (ບໍ່ບັງຄັບ)",
  ],
  "cargoSearch": ["화물번호로 검색", "Find by cargo number", "ຄົ້ນດ້ວຍເລກສິນຄ້າ"],
  "unlinked": ["별도 국내배송", "Standalone domestic delivery", "ການຈັດສົ່ງແຍກ"],
  "receiver": ["수취인 이름", "Recipient name", "ຊື່ຜູ້ຮັບ"],
  "phone": ["수취인 전화번호", "Recipient phone", "ເບີໂທຜູ້ຮັບ"],
  "save": ["저장", "Save", "ບັນທຶກ"],
  "edit": ["수정", "Edit", "ແກ້ໄຂ"],
  "saved": ["송장을 저장했습니다.", "Waybill saved.", "ບັນທຶກໃບສົ່ງແລ້ວ."],
  "more": ["다음 페이지", "Next page", "ໜ້າຕໍ່ໄປ"],
  "prev": ["이전 페이지", "Previous page", "ໜ້າກ່ອນ"],
  "registered": ["송장 등록", "Registered", "ລົງທະບຽນ"],
  "accepted": ["접수", "Accepted", "ຮັບແລ້ວ"],
  "in_transit": ["이동 중", "In transit", "ກຳລັງຂົນສົ່ງ"],
  "ready_for_pickup": [
    "도착 · 수령 대기",
    "Ready for collection",
    "ຮອດແລ້ວ · ລໍຖ້າຮັບ",
  ],
  "out_for_delivery": ["배송 중", "Out for delivery", "ກຳລັງຈັດສົ່ງ"],
  "delivered": ["배송 완료", "Delivered", "ຈັດສົ່ງສຳເລັດ"],
  "returned": ["반송", "Returned", "ສົ່ງຄືນ"],
  "exception": ["확인 필요", "Needs attention", "ຕ້ອງກວດສອບ"],
  "unknown": ["상태 확인 필요", "Status unconfirmed", "ລໍຖ້າຢືນຢັນ"],
  "verify": [
    "배송사 인증이 필요합니다. 배송사 사이트에서 확인하거나 담당자가 이력을 등록할 수 있습니다.",
    "Carrier verification is required. Open the carrier website or ask staff to record an update.",
    "ຕ້ອງຢືນຢັນໃນເວັບຂົນສົ່ງ ຫຼື ໃຫ້ພະນັກງານບັນທຶກ.",
  ],
  "connection": [
    "배송사 자동 연동을 준비 중입니다. 현재 등록된 이력과 사진을 확인할 수 있습니다.",
    "Automatic carrier connection is pending. Registered events and photos remain available.",
    "ກຳລັງກຽມເຊື່ອມຕໍ່ຂົນສົ່ງ. ເບິ່ງປະຫວັດ ແລະ ຮູບທີ່ບັນທຶກໄດ້.",
  ],
  "failed": [
    "배송사의 최신 정보를 가져오지 못했습니다. 마지막으로 저장된 이력을 표시합니다.",
    "Latest carrier data is unavailable. Showing the last saved history.",
    "ດຶງຂໍ້ມູນໃໝ່ບໍ່ໄດ້. ສະແດງປະຫວັດທີ່ບັນທຶກລ່າສຸດ.",
  ],
  "INVALID_TRACKING": [
    "송장번호 전체를 확인해 주세요 (6~40자).",
    "Enter a complete tracking number (6–40 characters).",
    "ກວດເລກໃບສົ່ງ (6–40 ຕົວ).",
  ],
  "DUPLICATE_TRACKING": [
    "같은 업체·송장번호가 이미 등록되어 있습니다.",
    "This carrier and tracking number already exist.",
    "ເລກໃບສົ່ງນີ້ມີແລ້ວ.",
  ],
  "RECORD_CHANGED": [
    "다른 곳에서 변경되었습니다. 다시 조회 후 저장하세요.",
    "This record changed. Reload before saving.",
    "ຂໍ້ມູນປ່ຽນແລ້ວ. ໂຫຼດຄືນກ່ອນບັນທຶກ.",
  ],
  "FILE_TOO_LARGE": [
    "사진은 5MB 이하로 선택하세요.",
    "Choose a photo smaller than 5MB.",
    "ເລືອກຮູບບໍ່ເກີນ 5MB.",
  ],
  "INVALID_IMAGE": [
    "JPG, PNG, WebP 사진만 등록할 수 있습니다.",
    "Use a JPG, PNG or WebP photo.",
    "ໃຊ້ຮູບ JPG, PNG ຫຼື WebP.",
  ],
  "LOGIN_REQUIRED": [
    "로그인 후 조회할 수 있습니다.",
    "Sign in to track a parcel.",
    "ເຂົ້າລະບົບເພື່ອຕິດຕາມ.",
  ],
  "FORBIDDEN": [
    "등록·수정 권한이 없습니다.",
    "You do not have permission to edit.",
    "ບໍ່ມີສິດແກ້ໄຂ.",
  ],
  "TOO_MANY_REQUESTS": [
    "잠시 후 다시 조회해 주세요.",
    "Please wait a minute before trying again.",
    "ກະລຸນາລໍຖ້າໜຶ່ງນາທີ.",
  ],
  "REQUEST_FAILED": [
    "요청을 처리하지 못했습니다. 다시 시도해 주세요.",
    "The request failed. Please try again.",
    "ດຳເນີນການບໍ່ໄດ້. ລອງໃໝ່.",
  ],
};
