// Generated by tool/generate_route_geometry.py.
import 'dart:ui';
import 'dart:math' as math;

Path sharedSeaRoutePath() => Path()..moveTo(563,106)..cubicTo(564,150,545,185,515,220)..cubicTo(485,239,449,258,448,287)..cubicTo(430,330,402,368,346,404)..cubicTo(315,424,292,445,268,463)..cubicTo(240,482,197,472,180,450)..cubicTo(167,434,163,420,169,409);

void drawSharedRouteVehicle(Canvas canvas, String vehicle) {
  switch (vehicle) {
    case 'truck':
      final p0 = Path()..moveTo(-24,-10)..lineTo(6,-10)..lineTo(6,7)..lineTo(-24,7)..close();
      canvas.drawPath(p0, Paint()..color = const Color(0xFFEEFAFF));
      canvas.drawPath(p0, Paint()..color = const Color(0xFF55C5E2)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p1 = Path()..moveTo(6,-3)..lineTo(16,-3)..lineTo(23,4)..lineTo(23,7)..lineTo(6,7)..close();
      canvas.drawPath(p1, Paint()..color = const Color(0xFFEEFAFF));
      canvas.drawPath(p1, Paint()..color = const Color(0xFF55C5E2)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p2 = Path()..moveTo(-20,-6)..lineTo(-14,-6)..lineTo(-14,4)..lineTo(-20,4)..close();
      canvas.drawPath(p2, Paint()..color = const Color(0xFF2F6E9E));
      canvas.drawPath(p2, Paint()..color = const Color(0xFF55C5E2)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p3 = Path()..moveTo(-12,-6)..lineTo(-6,-6)..lineTo(-6,4)..lineTo(-12,4)..close();
      canvas.drawPath(p3, Paint()..color = const Color(0xFF2F6E9E));
      canvas.drawPath(p3, Paint()..color = const Color(0xFF55C5E2)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p4 = Path()..moveTo(-4,-6)..lineTo(2,-6)..lineTo(2,4)..lineTo(-4,4)..close();
      canvas.drawPath(p4, Paint()..color = const Color(0xFF2F6E9E));
      canvas.drawPath(p4, Paint()..color = const Color(0xFF55C5E2)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p5 = Path()..moveTo(-11.5,9.0)..lineTo(-11.766,10.339)..lineTo(-12.525,11.475)..lineTo(-13.661,12.234)..lineTo(-15.0,12.5)..lineTo(-16.339,12.234)..lineTo(-17.475,11.475)..lineTo(-18.234,10.339)..lineTo(-18.5,9.0)..lineTo(-18.234,7.661)..lineTo(-17.475,6.525)..lineTo(-16.339,5.766)..lineTo(-15.0,5.5)..lineTo(-13.661,5.766)..lineTo(-12.525,6.525)..lineTo(-11.766,7.661)..close();
      canvas.drawPath(p5, Paint()..color = const Color(0xFF09284C));
      canvas.drawPath(p5, Paint()..color = const Color(0xFFFFFFFF)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p6 = Path()..moveTo(18.5,9.0)..lineTo(18.234,10.339)..lineTo(17.475,11.475)..lineTo(16.339,12.234)..lineTo(15.0,12.5)..lineTo(13.661,12.234)..lineTo(12.525,11.475)..lineTo(11.766,10.339)..lineTo(11.5,9.0)..lineTo(11.766,7.661)..lineTo(12.525,6.525)..lineTo(13.661,5.766)..lineTo(15.0,5.5)..lineTo(16.339,5.766)..lineTo(17.475,6.525)..lineTo(18.234,7.661)..close();
      canvas.drawPath(p6, Paint()..color = const Color(0xFF09284C));
      canvas.drawPath(p6, Paint()..color = const Color(0xFFFFFFFF)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      break;
    case 'ship':
      final p0 = Path()..moveTo(-28,4)..lineTo(28,4)..lineTo(18,14)..lineTo(-18,14)..close();
      canvas.drawPath(p0, Paint()..color = const Color(0xFFEEFAFF));
      canvas.drawPath(p0, Paint()..color = const Color(0xFF55C5E2)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p1 = Path()..moveTo(-20,-11)..lineTo(-9,-11)..lineTo(-9,3)..lineTo(-20,3)..close();
      canvas.drawPath(p1, Paint()..color = const Color(0xFFE6A840));
      canvas.drawPath(p1, Paint()..color = const Color(0xFF55C5E2)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p2 = Path()..moveTo(-8,-11)..lineTo(3,-11)..lineTo(3,3)..lineTo(-8,3)..close();
      canvas.drawPath(p2, Paint()..color = const Color(0xFFE6A840));
      canvas.drawPath(p2, Paint()..color = const Color(0xFF55C5E2)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p3 = Path()..moveTo(4,-11)..lineTo(15,-11)..lineTo(15,3)..lineTo(4,3)..close();
      canvas.drawPath(p3, Paint()..color = const Color(0xFFE6A840));
      canvas.drawPath(p3, Paint()..color = const Color(0xFF55C5E2)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p4 = Path()..moveTo(-29,16)..cubicTo(-22,13,-17,19,-10,16)..cubicTo(-3,13,2,19,9,16)..cubicTo(16,13,21,19,29,16);
      canvas.drawPath(p4, Paint()..color = const Color(0x00000000));
      canvas.drawPath(p4, Paint()..color = const Color(0xFF6BD6EF)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      break;
    case 'plane':
      final p0 = Path()..moveTo(-19,0)..lineTo(-5,-5)..lineTo(1,-16)..lineTo(6,-16)..lineTo(3,-3)..lineTo(19,0)..lineTo(3,4)..lineTo(6,16)..lineTo(1,16)..lineTo(-5,5)..close();
      canvas.drawPath(p0, Paint()..color = const Color(0xFFFFFFFF));
      canvas.drawPath(p0, Paint()..color = const Color(0xFFE6A043)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      break;
  }
}
const double routeMapMinZoom = 1.0;
const double routeMapMaxZoom = 4.0;
const double routeMapButtonFactor = 1.4;
const double routeMapWheelScaleFactor = 200.0;
const double routeMapVehicleZoomExponent = 0.65;
double routeVehicleZoomScale(double zoom) => math.pow(zoom.clamp(routeMapMinZoom, routeMapMaxZoom), -routeMapVehicleZoomExponent).toDouble();
