// Generated by tool/generate_route_geometry.py.
import 'dart:ui';

Path sharedSeaRoutePath() => Path()..moveTo(563,106)..cubicTo(564,150,545,185,525,220)..cubicTo(520,240,529,270,523,295)..cubicTo(511,333,428,369,346,404)..cubicTo(315,424,292,445,268,463)..cubicTo(240,482,197,472,180,450)..cubicTo(167,434,163,420,169,409);

void drawSharedRouteVehicle(Canvas canvas, String vehicle) {
  switch (vehicle) {
    case 'truck':
      final p0 = Path()..moveTo(-15,-20)..lineTo(-10,-20)..lineTo(-10,-11)..lineTo(-15,-11)..close();
      canvas.drawPath(p0, Paint()..color = const Color(0xFF09284C));
      canvas.drawPath(p0, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p1 = Path()..moveTo(10,-20)..lineTo(15,-20)..lineTo(15,-11)..lineTo(10,-11)..close();
      canvas.drawPath(p1, Paint()..color = const Color(0xFF09284C));
      canvas.drawPath(p1, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p2 = Path()..moveTo(-15,13)..lineTo(-10,13)..lineTo(-10,22)..lineTo(-15,22)..close();
      canvas.drawPath(p2, Paint()..color = const Color(0xFF09284C));
      canvas.drawPath(p2, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p3 = Path()..moveTo(10,13)..lineTo(15,13)..lineTo(15,22)..lineTo(10,22)..close();
      canvas.drawPath(p3, Paint()..color = const Color(0xFF09284C));
      canvas.drawPath(p3, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p4 = Path()..moveTo(-11,-16)..lineTo(-9,-26)..lineTo(9,-26)..lineTo(11,-16)..lineTo(11,-6)..lineTo(-11,-6)..close();
      canvas.drawPath(p4, Paint()..color = const Color(0xFFF1FBFF));
      canvas.drawPath(p4, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p5 = Path()..moveTo(-8,-20)..lineTo(8,-20)..lineTo(8,-13)..lineTo(-8,-13)..close();
      canvas.drawPath(p5, Paint()..color = const Color(0xFF2F6E9E));
      canvas.drawPath(p5, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p6 = Path()..moveTo(-11,-5)..lineTo(11,-5)..lineTo(11,26)..lineTo(-11,26)..close();
      canvas.drawPath(p6, Paint()..color = const Color(0xFFF1FBFF));
      canvas.drawPath(p6, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p7 = Path()..moveTo(-7,0)..lineTo(7,0)..lineTo(7,21)..lineTo(-7,21)..close();
      canvas.drawPath(p7, Paint()..color = const Color(0xFF2F6E9E));
      canvas.drawPath(p7, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      break;
    case 'ship':
      final p0 = Path()..moveTo(0,-32)..lineTo(15,-15)..lineTo(15,23)..lineTo(10,29)..lineTo(-10,29)..lineTo(-15,23)..lineTo(-15,-15)..close();
      canvas.drawPath(p0, Paint()..color = const Color(0xFFF1FBFF));
      canvas.drawPath(p0, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p1 = Path()..moveTo(-10,13)..lineTo(10,13)..lineTo(10,22)..lineTo(-10,22)..close();
      canvas.drawPath(p1, Paint()..color = const Color(0xFF2F6E9E));
      canvas.drawPath(p1, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p2 = Path()..moveTo(-9,-12)..lineTo(-1,-12)..lineTo(-1,-2)..lineTo(-9,-2)..close();
      canvas.drawPath(p2, Paint()..color = const Color(0xFFE6A840));
      canvas.drawPath(p2, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p3 = Path()..moveTo(1,-12)..lineTo(9,-12)..lineTo(9,-2)..lineTo(1,-2)..close();
      canvas.drawPath(p3, Paint()..color = const Color(0xFFE6A840));
      canvas.drawPath(p3, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p4 = Path()..moveTo(-9,1)..lineTo(-1,1)..lineTo(-1,11)..lineTo(-9,11)..close();
      canvas.drawPath(p4, Paint()..color = const Color(0xFFE6A840));
      canvas.drawPath(p4, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      final p5 = Path()..moveTo(1,1)..lineTo(9,1)..lineTo(9,11)..lineTo(1,11)..close();
      canvas.drawPath(p5, Paint()..color = const Color(0xFFE6A840));
      canvas.drawPath(p5, Paint()..color = const Color(0xFF5ED2EB)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      break;
    case 'plane':
      final p0 = Path()..moveTo(0,-29)..lineTo(4,-20)..lineTo(5,-7)..lineTo(27,9)..lineTo(27,14)..lineTo(5,7)..lineTo(4,21)..lineTo(12,26)..lineTo(12,29)..lineTo(0,26)..lineTo(-12,29)..lineTo(-12,26)..lineTo(-4,21)..lineTo(-5,7)..lineTo(-27,14)..lineTo(-27,9)..lineTo(-5,-7)..lineTo(-4,-20)..close();
      canvas.drawPath(p0, Paint()..color = const Color(0xFFFFFFFF));
      canvas.drawPath(p0, Paint()..color = const Color(0xFFE6A043)..style = PaintingStyle.stroke..strokeWidth = 1.5..strokeJoin = StrokeJoin.round);
      break;
  }
}
