// Generated by tool/generate_shared_ui_text.py. Edit shared-ui-text/contract.json.
const sharedTextAliases = <String, String>{
  "domestic.title": "domesticTracking",
  "domesticManage": "domesticTracking",
  "adminMenu.domesticTracking": "domesticTracking",
  "adminMenu.localDeliveries": "localDeliveries",
  "domestic.manage": "domesticTracking"
};
const sharedAppTextKeys = <String, String>{
  "add_box": "quote.addBox",
  "address": "address",
  "ai_consult": "aiTitle",
  "arrival_expected": "routeNetwork_eta",
  "box": "quote.box",
  "box_packing": "quote.packing",
  "change_password": "passwordChange",
  "company": "company",
  "consult_open": "consultMenu",
  "contact": "contactTitle",
  "delete": "delete",
  "delete_account": "accountDelete",
  "discount": "statement-preview.statementDocumentHtml.discount",
  "home": "homeMenu",
  "home_title": "layout.strong.lkGroup",
  "invoice_number": "invoice",
  "no_results": "textManager.empty",
  "notice": "notice",
  "notice_title": "notice",
  "password": "password",
  "phone": "phone",
  "quantity": "quantity",
  "quote_title": "quote.title",
  "route": "route",
  "schedule": "schedule",
  "sign_out": "logout",
  "sign_up": "signup",
  "tracking": "cargo",
  "tracking_title": "cargo",
  "voyage": "voyage",
  "year": "year"
};
const sharedKoreanTextKeys = <String, String>{
  "LK Group 블로그": "contact.channel.naver",
  "LK Group 사무실 위치": "contact.channel.google_maps",
  "LK그룹 카카오톡 단톡방": "contact.channel.kakao_group",
  "WhatsApp(한국어, Eng, ລາວ)": "contact.channel.whatsapp",
  "검색": "search",
  "견적 요청 관리": "adminMenu.quoteRequests",
  "고객 리스트": "adminMenu.customers",
  "고객 정보 편집": "receipt.customer",
  "공지 및 안내 관리": "adminMenu.notices",
  "공지사항 관리": "notices",
  "관리자 확인": "quote.viewed",
  "관리자 회신": "quote.adminReply",
  "기준 환율 입력": "adminMenu.exchange",
  "기타 비용": "quote.extra",
  "기타 연락처": "quote.otherContact",
  "내용": "quote.content",
  "년도": "year",
  "닫기": "aiClose",
  "바로 삭제": "quote.hide",
  "박스": "quote.box",
  "변경": "update",
  "비용 이름": "receipt.name",
  "삭제": "delete",
  "삭제 대기중": "parity.deletedRoutes",
  "선적 일정 관리": "adminMenu.schedules",
  "송장번호": "invoice",
  "수량": "quantity",
  "수정": "edit",
  "시내.지방 배송 list 관리": "localDeliveries",
  "암호": "password",
  "오픈상담톡(한국어, Eng, ລາວ)": "contact.channel.kakao_open",
  "운송 경로": "route",
  "이 영수번호에 묶인 {count}개 화물에 동일하게 적용됩니다.": "receipt-management.openReceiptCustomerEditor.appliesToAllCargoRowsIn",
  "이름": "name",
  "이메일": "email",
  "잠금 해제": "admin-parity.renderExcelBulkRows.unlocked",
  "저장": "save",
  "직접 입력 (선택)": "app.contentManualLabel.manualEntryOptional",
  "추가": "add",
  "추가 할인": "excel-management.fetchSettlement.additionalDiscount",
  "추가 할인명": "receipt.discountName",
  "취소": "admin-parity.renderRouteDevelopmentEditor.cancel",
  "하역 자료 관리": "adminMenu.unloading",
  "할인 적용 관리": "adminMenu.discounts",
  "할인율": "admin.discount",
  "할인율은 0~100 사이로 입력해 주세요.": "receipt.percentInvalid",
  "항차": "voyage",
  "항차별 총액 관리": "adminMenu.voyageTotals",
  "현재": "app.renderCorrections.current",
  "화물 내용 변경 승인 관리": "adminMenu.corrections",
  "화물 데이타 엑셀 파일 관리": "adminMenu.excelFiles",
  "화물 종합 관리": "adminMenu.cargo",
  "화물번호": "box",
  "확인 전": "quote.waiting",
  "회신 완료": "quote.replied",
  "회원 로그인": "loginTitle",
  "회원 종합 관리": "adminMenu.members",
  "회원 탈퇴": "accountDelete"
};
const sharedTextDefaults = <String, Map<String, String>>{
  "account": {
  "ko": "내 정보",
  "en": "My Account",
  "lo": "ບັນຊີຂອງຂ້ອຍ"
},
  "accountDelete": {
  "ko": "회원 탈퇴",
  "en": "Delete Account",
  "lo": "ລົບບັນຊີ"
},
  "add": {
  "ko": "추가",
  "en": "Add",
  "lo": "ເພີ່ມ"
},
  "address": {
  "ko": "주소",
  "en": "Address",
  "lo": "ທີ່ຢູ່"
},
  "admin-parity.renderExcelBulkRows.unlocked": {
  "ko": "잠금 해제",
  "en": "Unlocked",
  "lo": "ປົດລັອກແລ້ວ"
},
  "admin-parity.renderRouteDevelopmentEditor.cancel": {
  "ko": "취소",
  "en": "Cancel",
  "lo": "ຍົກເລີກ"
},
  "admin.discount": {
  "ko": "할인율",
  "en": "Discount",
  "lo": "ອັດຕາສ່ວນຫຼຸດ"
},
  "adminMenu.cargo": {
  "ko": "화물 종합 관리",
  "en": "Cargo management",
  "lo": "ຈັດການສິນຄ້າ"
},
  "adminMenu.corrections": {
  "ko": "화물 내용 변경 승인 관리",
  "en": "Cargo change approvals",
  "lo": "ອະນຸມັດການປ່ຽນຂໍ້ມູນສິນຄ້າ"
},
  "adminMenu.customers": {
  "ko": "고객 리스트",
  "en": "Customer list",
  "lo": "ລາຍຊື່ລູກຄ້າ"
},
  "adminMenu.discounts": {
  "ko": "할인 적용 관리",
  "en": "Discount management",
  "lo": "ຈັດການສ່ວນຫຼຸດ"
},
  "adminMenu.excelFiles": {
  "ko": "화물 데이터 엑셀 파일 관리",
  "en": "Cargo Excel files",
  "lo": "ຈັດການໄຟລ໌ Excel ສິນຄ້າ"
},
  "adminMenu.exchange": {
  "ko": "기준 환율 입력",
  "en": "Reference exchange rates",
  "lo": "ປ້ອນອັດຕາແລກປ່ຽນອ້າງອີງ"
},
  "adminMenu.members": {
  "ko": "회원 종합 관리",
  "en": "Member management",
  "lo": "ຈັດການສະມາຊິກ"
},
  "adminMenu.notices": {
  "ko": "공지 및 안내 관리",
  "en": "Notices and information",
  "lo": "ຈັດການແຈ້ງການ ແລະ ຂໍ້ມູນ"
},
  "adminMenu.quoteRequests": {
  "ko": "견적 요청 관리",
  "en": "Quotation requests",
  "lo": "ຈັດການຄຳຂໍລາຄາ"
},
  "adminMenu.schedules": {
  "ko": "선적 일정 관리",
  "en": "Shipment schedules",
  "lo": "ຈັດການຕາຕະລາງຂົນສົ່ງ"
},
  "adminMenu.unloading": {
  "ko": "하역 자료 관리",
  "en": "Unloading records",
  "lo": "ຈັດການຂໍ້ມູນຂົນຖ່າຍ"
},
  "adminMenu.voyageTotals": {
  "ko": "항차별 총액 관리",
  "en": "Voyage totals",
  "lo": "ຈັດການຍອດລວມຕາມຖ້ຽວ"
},
  "aiClose": {
  "ko": "닫기",
  "en": "Close",
  "lo": "ປິດ"
},
  "aiTitle": {
  "ko": "AI 상담",
  "en": "AI chat",
  "lo": "ປຶກສາ AI"
},
  "app.contentManualLabel.manualEntryOptional": {
  "ko": "직접 입력 (선택)",
  "en": "Manual entry (optional)",
  "lo": "ປ້ອນເອງ (ບໍ່ບັງຄັບ)"
},
  "app.renderCorrections.current": {
  "ko": "현재",
  "en": "Current",
  "lo": "ປັດຈຸບັນ"
},
  "box": {
  "ko": "화물번호",
  "en": "Cargo No.",
  "lo": "ເລກສິນຄ້າ"
},
  "cargo": {
  "ko": "화물 조회",
  "en": "Cargo Search",
  "lo": "ຄົ້ນຫາສິນຄ້າ"
},
  "company": {
  "ko": "회사명",
  "en": "Company",
  "lo": "ບໍລິສັດ"
},
  "consultMenu": {
  "ko": "상담하기",
  "en": "Contact a consultant",
  "lo": "ຕິດຕໍ່ປຶກສາ"
},
  "contact.channel.google_maps": {
  "ko": "LK Group 사무실 위치",
  "en": "LK Group Office Location",
  "lo": "ທີ່ຕັ້ງສຳນັກງານ LK Group"
},
  "contact.channel.kakao_group": {
  "ko": "LK그룹 카카오톡 단톡방",
  "en": "LK Group KakaoTalk Group Chat",
  "lo": "ກຸ່ມສົນທະນາ KakaoTalk ຂອງ LK Group"
},
  "contact.channel.kakao_open": {
  "ko": "오픈상담톡(한국어, Eng, ລາວ)",
  "en": "Open chat (Korean, English, Lao)",
  "lo": "ສົນທະນາເປີດ (ເກົາຫຼີ, ອັງກິດ, ລາວ)"
},
  "contact.channel.naver": {
  "ko": "LK Group 블로그",
  "en": "LK Group Blog",
  "lo": "ບລັອກ LK Group"
},
  "contact.channel.whatsapp": {
  "ko": "WhatsApp(한국어, Eng, ລາວ)",
  "en": "WhatsApp (Korean, English, Lao)",
  "lo": "WhatsApp (ເກົາຫຼີ, ອັງກິດ, ລາວ)"
},
  "contactTitle": {
  "ko": "상담 및 연락처",
  "en": "Consultation & Contact",
  "lo": "ປຶກສາ ແລະ ຕິດຕໍ່"
},
  "delete": {
  "ko": "삭제",
  "en": "Delete",
  "lo": "ລົບ"
},
  "domestic.AMBIGUOUS_STATEMENT": {
  "ko": "같은 번호가 여러 명세서에 있습니다. LKS 03처럼 전체 명세서 번호를 입력하세요.",
  "en": "More than one statement matches. Enter the full statement number, such as LKS 03.",
  "lo": "ພົບຫຼາຍໃບລາຍການ. ປ້ອນເລກຄົບ ເຊັ່ນ LKS 03."
},
  "domestic.CARGO_REQUIRED": {
  "ko": "연결할 명세서·화물을 먼저 선택하세요.",
  "en": "Select the statement / cargo first.",
  "lo": "ເລືອກໃບລາຍການ / ສິນຄ້າກ່ອນ."
},
  "domestic.DUPLICATE_TRACKING": {
  "ko": "같은 업체·송장번호가 이미 등록되어 있습니다.",
  "en": "This carrier and tracking number already exist.",
  "lo": "ເລກໃບສົ່ງນີ້ມີແລ້ວ."
},
  "domestic.FILE_TOO_LARGE": {
  "ko": "사진은 장당 5MB, 이번 선택 합계 15MB 이하여야 합니다.",
  "en": "Photos must be at most 5MB each and 15MB total per selection.",
  "lo": "ຮູບຕ້ອງບໍ່ເກີນ 5MB ຕໍ່ຮູບ ແລະ ລວມ 15MB ຕໍ່ຄັ້ງ."
},
  "domestic.FORBIDDEN": {
  "ko": "이 명세서를 조회하거나 수정할 권한이 없습니다.",
  "en": "You do not have access to this statement.",
  "lo": "ບໍ່ມີສິດເບິ່ງ ຫຼື ແກ້ໄຂ."
},
  "domestic.INVALID_BATCH": {
  "ko": "송장번호는 한 번에 1~20개까지 등록할 수 있습니다.",
  "en": "Register 1–20 tracking numbers at a time.",
  "lo": "ລົງທະບຽນໄດ້ 1–20 ເລກຕໍ່ຄັ້ງ."
},
  "domestic.INVALID_IMAGE": {
  "ko": "JPG, PNG, WebP 사진만 등록할 수 있습니다.",
  "en": "Use JPG, PNG or WebP.",
  "lo": "ໃຊ້ຮູບ JPG, PNG ຫຼື WebP."
},
  "domestic.INVALID_LINK_SCOPE": {
  "ko": "연결 방식을 확인하세요.",
  "en": "Check the link method.",
  "lo": "ກວດວິທີເຊື່ອມ."
},
  "domestic.INVALID_REFERENCE": {
  "ko": "관리번호 구분과 전체 번호를 확인하세요. 영문·숫자·점·하이픈·밑줄·슬래시를 사용할 수 있습니다.",
  "en": "Check the reference type and full number. Use letters, digits, dots, hyphens, underscores or slashes.",
  "lo": "ກວດປະເພດ ແລະ ເລກອ້າງອີງ. ໃຊ້ອັກສອນອັງກິດ, ຕົວເລກ, ຈຸດ, ຂີດ ຫຼື ເຄື່ອງໝາຍທັບ."
},
  "domestic.INVALID_STATEMENT": {
  "ko": "명세서 번호 또는 화물번호 전체를 입력하세요.",
  "en": "Enter the complete statement or cargo number.",
  "lo": "ປ້ອນເລກໃບລາຍການ ຫຼື ເລກສິນຄ້າຄົບຖ້ວນ."
},
  "domestic.INVALID_TRACKING": {
  "ko": "송장번호 전체를 확인해 주세요 (6~40자).",
  "en": "Enter a complete tracking number (6–40 characters).",
  "lo": "ກວດເລກໃບສົ່ງ (6–40 ຕົວ)."
},
  "domestic.INVALID_YEAR": {
  "ko": "연도를 확인해 주세요.",
  "en": "Check the year.",
  "lo": "ກວດປີ."
},
  "domestic.LOGIN_REQUIRED": {
  "ko": "로그인 후 조회할 수 있습니다.",
  "en": "Sign in to track a parcel.",
  "lo": "ເຂົ້າລະບົບເພື່ອຕິດຕາມ."
},
  "domestic.NARROW_SEARCH": {
  "ko": "운송경로·연도·항차를 추가해 검색 범위를 좁혀 주세요.",
  "en": "Add a route, year or voyage to narrow the search.",
  "lo": "ເລືອກເສັ້ນທາງ, ປີ ຫຼື ຖ້ຽວເພື່ອຈຳກັດການຄົ້ນຫາ."
},
  "domestic.RECORD_CHANGED": {
  "ko": "다른 곳에서 변경되었습니다. 다시 조회 후 저장하세요.",
  "en": "This record changed. Reload before saving.",
  "lo": "ຂໍ້ມູນປ່ຽນແລ້ວ."
},
  "domestic.REQUEST_FAILED": {
  "ko": "요청을 처리하지 못했습니다. 다시 시도해 주세요.",
  "en": "The request failed.",
  "lo": "ດຳເນີນການບໍ່ໄດ້."
},
  "domestic.STATEMENT_NOT_FOUND": {
  "ko": "선택한 경로·연도·항차에서 명세서를 찾지 못했습니다.",
  "en": "No statement matches the selected route, year and voyage.",
  "lo": "ບໍ່ພົບໃບລາຍການໃນເສັ້ນທາງ, ປີ ແລະ ຖ້ຽວທີ່ເລືອກ."
},
  "domestic.STATEMENT_REQUIRED": {
  "ko": "경로·연도·항차와 명세서 번호를 입력한 뒤 명세서 확인을 눌러 주세요.",
  "en": "Choose the route, year and voyage, enter the number, then confirm the statement.",
  "lo": "ເລືອກເສັ້ນທາງ, ປີ, ຖ້ຽວ ແລະ ປ້ອນເລກ ແລ້ວກວດໃບລາຍການ."
},
  "domestic.TOO_MANY_PHOTOS": {
  "ko": "기존 사진을 포함해 송장당 최대 10장까지 등록할 수 있습니다.",
  "en": "Each waybill can have up to 10 photos, including existing photos.",
  "lo": "ແຕ່ລະໃບສົ່ງມີໄດ້ສູງສຸດ 10 ຮູບ ລວມຮູບເກົ່າ."
},
  "domestic.TOO_MANY_REQUESTS": {
  "ko": "잠시 후 다시 조회해 주세요.",
  "en": "Please wait before trying again.",
  "lo": "ກະລຸນາລໍຖ້າ."
},
  "domestic.accepted": {
  "ko": "접수",
  "en": "Accepted",
  "lo": "ຮັບແລ້ວ"
},
  "domestic.add": {
  "ko": "배송정보 연결",
  "en": "Link delivery",
  "lo": "ເຊື່ອມຂໍ້ມູນຈັດສົ່ງ"
},
  "domestic.addWaybill": {
  "ko": "송장번호 추가",
  "en": "Add tracking number",
  "lo": "ເພີ່ມເລກໃບສົ່ງ"
},
  "domestic.all": {
  "ko": "업체 전체",
  "en": "All carriers",
  "lo": "ທຸກບໍລິສັດ"
},
  "domestic.ansCandidate": {
  "ko": "ANS 번호 형식과 유사합니다. 송장 사진을 확인한 후 업체를 선택하세요.",
  "en": "This resembles an ANS number. Check the waybill photo before selecting the carrier.",
  "lo": "ຮູບແບບຄ້າຍເລກ ANS. ກວດຮູບໃບສົ່ງກ່ອນເລືອກ."
},
  "domestic.any": {
  "ko": "전체",
  "en": "Any",
  "lo": "ທັງໝົດ"
},
  "domestic.autoRefreshHint": {
  "ko": "등록·조회 시 배송 이력을 자동 확인합니다. 화면을 열어 둔 동안 5분마다 갱신합니다.",
  "en": "History is checked automatically when saving or viewing, and every 5 minutes while this screen is open.",
  "lo": "ກວດປະຫວັດອັດຕະໂນມັດເມື່ອບັນທຶກ ຫຼື ເບິ່ງ ແລະ ທຸກ 5 ນາທີຂະນະເປີດໜ້ານີ້."
},
  "domestic.cargo": {
  "ko": "명세서·화물 선택",
  "en": "Select statement / cargo",
  "lo": "ເລືອກໃບລາຍການ / ສິນຄ້າ"
},
  "domestic.cargoCount": {
  "ko": "포함 화물",
  "en": "Cargo items",
  "lo": "ລາຍການສິນຄ້າ"
},
  "domestic.cargoSearch": {
  "ko": "명세서 번호 또는 화물번호로 검색",
  "en": "Find by statement or cargo number",
  "lo": "ຄົ້ນດ້ວຍເລກໃບລາຍການ ຫຼື ເລກສິນຄ້າ"
},
  "domestic.carrier": {
  "ko": "배송업체",
  "en": "Carrier",
  "lo": "ບໍລິສັດຂົນສົ່ງ"
},
  "domestic.carrierHint": {
  "ko": "번호 형식에 따른 참고 추천입니다. 송장에 적힌 배송업체를 확인해 선택하세요.",
  "en": "Suggestions use the number format only. Confirm the carrier printed on the waybill.",
  "lo": "ຄຳແນະນຳອີງຕາມຮູບແບບເລກເທົ່ານັ້ນ. ກວດບໍລິສັດທີ່ຢູ່ໃນໃບສົ່ງ."
},
  "domestic.carrierSource": {
  "ko": "배송사 기록",
  "en": "Carrier entry",
  "lo": "ບໍລິສັດບັນທຶກ"
},
  "domestic.checked": {
  "ko": "최근 조회",
  "en": "Last checked",
  "lo": "ກວດລ່າສຸດ"
},
  "domestic.city": {
  "ko": "시내",
  "en": "City",
  "lo": "ໃນເມືອງ"
},
  "domestic.confirmStatement": {
  "ko": "명세서 확인",
  "en": "Confirm statement",
  "lo": "ກວດໃບລາຍການ"
},
  "domestic.connection": {
  "ko": "배송사 자동 연동을 준비 중입니다. 현재 등록된 이력과 사진을 확인할 수 있습니다.",
  "en": "Automatic carrier connection is pending.",
  "lo": "ກຳລັງກຽມເຊື່ອມຕໍ່ຂົນສົ່ງ."
},
  "domestic.correctionHelp": {
  "ko": "업체나 송장번호를 정정하면 이전 배송사 이력은 초기화됩니다. 직접 등록한 이력과 사진은 유지됩니다.",
  "en": "Correcting the carrier or number resets carrier events. Manually recorded events and photos are retained.",
  "lo": "ການແກ້ບໍລິສັດ ຫຼື ເລກໃບສົ່ງຈະລ້າງປະຫວັດຈາກຂົນສົ່ງ. ປະຫວັດທີ່ບັນທຶກເອງ ແລະ ຮູບຍັງຢູ່."
},
  "domestic.delivered": {
  "ko": "배송 완료",
  "en": "Delivered",
  "lo": "ຈັດສົ່ງສຳເລັດ"
},
  "domestic.description": {
  "ko": "처리 내용",
  "en": "Event details",
  "lo": "ລາຍລະອຽດ"
},
  "domestic.domestic": {
  "ko": "국내배송",
  "en": "Domestic",
  "lo": "ພາຍໃນ"
},
  "domestic.ecommerce": {
  "ko": "전자상거래",
  "en": "E-commerce",
  "lo": "ອີຄອມເມີຊ"
},
  "domestic.edit": {
  "ko": "수정",
  "en": "Edit",
  "lo": "ແກ້ໄຂ"
},
  "domestic.empty": {
  "ko": "일치하는 명세서 또는 화물을 찾지 못했습니다.",
  "en": "No matching statement or cargo was found.",
  "lo": "ບໍ່ພົບໃບລາຍການ ຫຼື ສິນຄ້າ."
},
  "domestic.exampleStatement": {
  "ko": "예: LKS 03",
  "en": "Example: LKS 03",
  "lo": "ຕົວຢ່າງ: LKS 03"
},
  "domestic.exception": {
  "ko": "확인 필요",
  "en": "Needs attention",
  "lo": "ຕ້ອງກວດສອບ"
},
  "domestic.express": {
  "ko": "특송",
  "en": "Express",
  "lo": "ດ່ວນ"
},
  "domestic.failed": {
  "ko": "배송사의 최신 정보를 가져오지 못했습니다. 마지막으로 저장된 이력을 표시합니다.",
  "en": "Latest carrier data is unavailable. Showing the last saved history.",
  "lo": "ດຶງຂໍ້ມູນໃໝ່ບໍ່ໄດ້. ສະແດງປະຫວັດທີ່ບັນທຶກລ່າສຸດ."
},
  "domestic.filtersEmpty": {
  "ko": "선택할 운송 데이터가 없습니다. 번호만으로 조회할 수 있습니다.",
  "en": "No shipment filters are available. You can search by number only.",
  "lo": "ບໍ່ມີຂໍ້ມູນຂົນສົ່ງໃຫ້ເລືອກ. ຄົ້ນຫາດ້ວຍເລກໄດ້."
},
  "domestic.filtersFailed": {
  "ko": "검색 조건을 불러오지 못했습니다. 다시 시도하거나 번호만으로 조회하세요.",
  "en": "Filters could not be loaded. Retry or search by number only.",
  "lo": "ໂຫຼດເງື່ອນໄຂບໍ່ໄດ້. ລອງໃໝ່ ຫຼື ຄົ້ນຫາດ້ວຍເລກເທົ່ານັ້ນ."
},
  "domestic.filtersLoading": {
  "ko": "검색 조건을 불러오는 중…",
  "en": "Loading search filters…",
  "lo": "ກຳລັງໂຫຼດເງື່ອນໄຂຄົ້ນຫາ…"
},
  "domestic.hint": {
  "ko": "명세서 번호를 입력하면 연결된 배송을 한 번에 확인할 수 있습니다. 필요하면 운송경로·연도·항차로 범위를 좁혀 주세요.",
  "en": "Enter a statement number to see linked deliveries. Select a route, year or voyage if needed.",
  "lo": "ປ້ອນເລກໃບລາຍການເພື່ອເບິ່ງການຈັດສົ່ງ. ເລືອກເສັ້ນທາງ, ປີ ຫຼື ຖ້ຽວເມື່ອຈຳເປັນ."
},
  "domestic.history": {
  "ko": "배송 이력",
  "en": "Delivery history",
  "lo": "ປະຫວັດການຈັດສົ່ງ"
},
  "domestic.in_transit": {
  "ko": "이동 중",
  "en": "In transit",
  "lo": "ກຳລັງຂົນສົ່ງ"
},
  "domestic.inbound": {
  "ko": "라오스 입국 연계",
  "en": "Inbound",
  "lo": "ຂາເຂົ້າ"
},
  "domestic.kind": {
  "ko": "배송 구분",
  "en": "Delivery type",
  "lo": "ປະເພດຈັດສົ່ງ"
},
  "domestic.linkCargo": {
  "ko": "개별 화물 연결",
  "en": "Link individual cargo",
  "lo": "ເຊື່ອມສິນຄ້າແຕ່ລະລາຍການ"
},
  "domestic.linkLegacy": {
  "ko": "기존 송장만 등록된 배송",
  "en": "Existing delivery without a reference",
  "lo": "ການຈັດສົ່ງເກົ່າທີ່ບໍ່ມີເລກອ້າງອີງ"
},
  "domestic.linkMethod": {
  "ko": "연결 방식",
  "en": "Link method",
  "lo": "ວິທີເຊື່ອມ"
},
  "domestic.linkReference": {
  "ko": "별도 명세서·관리번호 연결",
  "en": "Link a separate reference",
  "lo": "ເຊື່ອມເລກອ້າງອີງແຍກ"
},
  "domestic.linkStatement": {
  "ko": "LK 명세서 연결",
  "en": "Link an LK statement",
  "lo": "ເຊື່ອມໃບລາຍການ LK"
},
  "domestic.linkTarget": {
  "ko": "연결 대상",
  "en": "Link target",
  "lo": "ເປົ້າໝາຍເຊື່ອມ"
},
  "domestic.list": {
  "ko": "등록된 배송정보",
  "en": "Registered deliveries",
  "lo": "ລາຍການຈັດສົ່ງ"
},
  "domestic.loading": {
  "ko": "연결된 배송정보를 확인하고 있습니다…",
  "en": "Checking linked deliveries…",
  "lo": "ກຳລັງກວດຂໍ້ມູນຈັດສົ່ງ…"
},
  "domestic.local": {
  "ko": "별도 국내배송",
  "en": "Separate domestic delivery",
  "lo": "ການຈັດສົ່ງພາຍໃນແຍກ"
},
  "domestic.location": {
  "ko": "처리 지점 / 위치",
  "en": "Branch / location",
  "lo": "ສາຂາ / ສະຖານທີ່"
},
  "domestic.lookupKind": {
  "ko": "조회 기준",
  "en": "Search by",
  "lo": "ຄົ້ນຫາຕາມ"
},
  "domestic.manageHint": {
  "ko": "LK 명세서별로 배송업체 송장과 사진, 배송 이력을 관리합니다.",
  "en": "Manage carrier waybills, photos and delivery history by LK statement.",
  "lo": "ຈັດການໃບສົ່ງ, ຮູບ ແລະ ປະຫວັດຕາມໃບລາຍການ LK."
},
  "domestic.manual": {
  "ko": "배송 이력 추가",
  "en": "Add delivery event",
  "lo": "ເພີ່ມປະຫວັດ"
},
  "domestic.mappingHelp": {
  "ko": "경로·연도·항차를 선택하고 LK 명세서 번호를 확인하세요. 선택한 명세서 전체에 배송 송장을 연결합니다.",
  "en": "Choose the route, year and voyage, then confirm the LK statement number. The waybill will link to the whole statement.",
  "lo": "ເລືອກເສັ້ນທາງ, ປີ ແລະ ຖ້ຽວ ແລ້ວກວດເລກໃບລາຍການ LK. ໃບສົ່ງຈະເຊື່ອມກັບໃບລາຍການທັງໝົດ."
},
  "domestic.more": {
  "ko": "다음 페이지",
  "en": "Next page",
  "lo": "ໜ້າຕໍ່ໄປ"
},
  "domestic.noEvents": {
  "ko": "아직 확인된 배송 이력이 없습니다.",
  "en": "No delivery events confirmed yet.",
  "lo": "ຍັງບໍ່ມີປະຫວັດທີ່ຢືນຢັນ."
},
  "domestic.noLinked": {
  "ko": "명세서는 확인됐지만 연결된 배송정보가 없습니다.",
  "en": "The statement was found, but no delivery is linked yet.",
  "lo": "ພົບໃບລາຍການແລ້ວ ແຕ່ຍັງບໍ່ມີການຈັດສົ່ງທີ່ເຊື່ອມ."
},
  "domestic.noPhoto": {
  "ko": "등록된 송장 사진이 없습니다.",
  "en": "No waybill photo registered.",
  "lo": "ຍັງບໍ່ມີຮູບໃບສົ່ງ."
},
  "domestic.noRecommendation": {
  "ko": "번호를 입력하면 업체를 추천합니다.",
  "en": "Enter a number to get a suggestion.",
  "lo": "ປ້ອນເລກເພື່ອຮັບຄຳແນະນຳ."
},
  "domestic.official": {
  "ko": "배송사 사이트에서 확인",
  "en": "Open carrier website",
  "lo": "ເບິ່ງເວັບຂົນສົ່ງ"
},
  "domestic.out_for_delivery": {
  "ko": "배송 중",
  "en": "Out for delivery",
  "lo": "ກຳລັງຈັດສົ່ງ"
},
  "domestic.outbound": {
  "ko": "라오스 출국 연계",
  "en": "Outbound",
  "lo": "ຂາອອກ"
},
  "domestic.phone": {
  "ko": "수취인 전화번호",
  "en": "Recipient phone",
  "lo": "ເບີໂທຜູ້ຮັບ"
},
  "domestic.photo": {
  "ko": "등록된 송장 사진",
  "en": "Waybill photo",
  "lo": "ຮູບໃບສົ່ງ"
},
  "domestic.photoHelp": {
  "ko": "선택한 사진은 이번에 등록하는 송장들에 함께 연결되며, 명세서 안에서 확인할 수 있습니다. JPG·PNG·WebP를 선택하세요.",
  "en": "Selected photos are shared by the waybills saved together and shown inside the statement. Choose JPG, PNG or WebP.",
  "lo": "ຮູບຈະເຊື່ອມກັບໃບສົ່ງທີ່ບັນທຶກພ້ອມກັນ ແລະ ສະແດງໃນໃບລາຍການ. ໃຊ້ JPG, PNG ຫຼື WebP."
},
  "domestic.photoInput": {
  "ko": "송장 사진 여러 장 선택 · 최대 10장, 장당 5MB, 합계 15MB",
  "en": "Select waybill photos · up to 10, 5MB each, 15MB total",
  "lo": "ເລືອກຫຼາຍຮູບ · ສູງສຸດ 10 ຮູບ, ຮູບລະ 5MB, ລວມ 15MB"
},
  "domestic.prev": {
  "ko": "이전 페이지",
  "en": "Previous page",
  "lo": "ໜ້າກ່ອນ"
},
  "domestic.province": {
  "ko": "지방",
  "en": "Province",
  "lo": "ຕ່າງແຂວງ"
},
  "domestic.ready_for_pickup": {
  "ko": "도착 · 수령 대기",
  "en": "Ready for collection",
  "lo": "ຮອດແລ້ວ · ລໍຖ້າຮັບ"
},
  "domestic.receiver": {
  "ko": "수취인 이름",
  "en": "Recipient name",
  "lo": "ຊື່ຜູ້ຮັບ"
},
  "domestic.recipientMasked": {
  "ko": "다른 고객의 이름과 연락처는 일부만 표시됩니다.",
  "en": "Another customer's name and phone are partially masked.",
  "lo": "ຊື່ ແລະ ເບີໂທຂອງລູກຄ້າອື່ນຖືກປິດບັງບາງສ່ວນ."
},
  "domestic.recommendation": {
  "ko": "번호 형식 추천",
  "en": "Number-format suggestion",
  "lo": "ແນະນຳຈາກຮູບແບບເລກ"
},
  "domestic.recommendationHelp": {
  "ko": "추천 업체는 직접 변경할 수 있습니다.",
  "en": "You can override the suggested carrier.",
  "lo": "ສາມາດປ່ຽນບໍລິສັດທີ່ແນະນຳໄດ້."
},
  "domestic.referenceHelp": {
  "ko": "전자상거래 또는 별도 국내배송에 사용하는 LK 관리번호를 입력하세요. 배송업체 송장번호는 아래에 따로 입력합니다.",
  "en": "Enter the LK reference used for e-commerce or separate domestic deliveries. Enter the carrier tracking number separately below.",
  "lo": "ປ້ອນເລກອ້າງອີງ LK ສຳລັບອີຄອມເມີຊ ຫຼື ການຈັດສົ່ງພາຍໃນແຍກ. ປ້ອນເລກໃບສົ່ງຂອງຂົນສົ່ງຢູ່ດ້ານລຸ່ມ."
},
  "domestic.referenceNumber": {
  "ko": "별도 명세서·관리번호",
  "en": "Separate statement / reference number",
  "lo": "ເລກໃບລາຍການ / ອ້າງອີງແຍກ"
},
  "domestic.referenceType": {
  "ko": "관리번호 구분",
  "en": "Reference type",
  "lo": "ປະເພດເລກອ້າງອີງ"
},
  "domestic.refresh": {
  "ko": "배송 이력 조회",
  "en": "Check delivery history",
  "lo": "ກວດປະຫວັດຈັດສົ່ງ"
},
  "domestic.registered": {
  "ko": "송장 등록",
  "en": "Registered",
  "lo": "ລົງທະບຽນ"
},
  "domestic.removePhoto": {
  "ko": "선택 사진 제외",
  "en": "Remove selected photo",
  "lo": "ເອົາຮູບທີ່ເລືອກອອກ"
},
  "domestic.removeWaybill": {
  "ko": "송장번호 삭제",
  "en": "Remove tracking number",
  "lo": "ລຶບເລກໃບສົ່ງ"
},
  "domestic.restricted": {
  "ko": "송장 사진은 해당 고객과 담당자만 볼 수 있습니다.",
  "en": "The photo is available to the recipient and authorized staff.",
  "lo": "ຮູບໃບສົ່ງສຳລັບຜູ້ຮັບ ແລະ ຜູ້ມີສິດ."
},
  "domestic.retry": {
  "ko": "다시 시도",
  "en": "Retry",
  "lo": "ລອງໃໝ່"
},
  "domestic.returned": {
  "ko": "반송",
  "en": "Returned",
  "lo": "ສົ່ງຄືນ"
},
  "domestic.route": {
  "ko": "운송경로",
  "en": "Route",
  "lo": "ເສັ້ນທາງ"
},
  "domestic.save": {
  "ko": "저장",
  "en": "Save",
  "lo": "ບັນທຶກ"
},
  "domestic.saved": {
  "ko": "배송정보를 저장했습니다.",
  "en": "Delivery saved.",
  "lo": "ບັນທຶກການຈັດສົ່ງແລ້ວ."
},
  "domestic.search": {
  "ko": "조회",
  "en": "Search",
  "lo": "ຄົ້ນຫາ"
},
  "domestic.selectCarrier": {
  "ko": "배송업체를 확인해 선택하세요",
  "en": "Confirm and select the carrier",
  "lo": "ກວດ ແລະ ເລືອກບໍລິສັດ"
},
  "domestic.service": {
  "ko": "운송 구분",
  "en": "Service",
  "lo": "ປະເພດບໍລິການ"
},
  "domestic.staff": {
  "ko": "직원 기록",
  "en": "Staff entry",
  "lo": "ພະນັກງານບັນທຶກ"
},
  "domestic.standalone": {
  "ko": "별도 국내배송",
  "en": "Standalone delivery",
  "lo": "ການຈັດສົ່ງແຍກ"
},
  "domestic.statement": {
  "ko": "명세서 번호 / 화물번호",
  "en": "Statement / cargo number",
  "lo": "ເລກໃບລາຍການ / ເລກສິນຄ້າ"
},
  "domestic.statementConfirmed": {
  "ko": "연결할 명세서 확인 완료",
  "en": "Statement confirmed for linking",
  "lo": "ຢືນຢັນໃບລາຍການທີ່ຈະເຊື່ອມແລ້ວ"
},
  "domestic.statementNumber": {
  "ko": "LK 명세서 번호",
  "en": "LK statement number",
  "lo": "ເລກໃບລາຍການ LK"
},
  "domestic.stepStatement": {
  "ko": "1. 연결할 LK 명세서 또는 관리번호",
  "en": "1. LK statement or reference to link",
  "lo": "1. ໃບລາຍການ LK ຫຼື ເລກອ້າງອີງ"
},
  "domestic.stepWaybill": {
  "ko": "2. 라오스 배송업체 송장",
  "en": "2. Lao carrier waybill",
  "lo": "2. ໃບສົ່ງຂອງບໍລິສັດຂົນສົ່ງລາວ"
},
  "domestic.summary": {
  "ko": "연결 배송정보",
  "en": "Linked deliveries",
  "lo": "ຂໍ້ມູນຈັດສົ່ງທີ່ເຊື່ອມ"
},
  "domestic.synced": {
  "ko": "배송사 확인",
  "en": "Carrier updated",
  "lo": "ອັບເດດຈາກຂົນສົ່ງ"
},
  "domestic.timezone": {
  "ko": "라오스 시간 · UTC+7",
  "en": "Laos time · UTC+7",
  "lo": "ເວລາລາວ · UTC+7"
},
  "domestic.tracking": {
  "ko": "국내배송 송장번호",
  "en": "Domestic tracking number",
  "lo": "ເລກໃບສົ່ງພາຍໃນ"
},
  "domestic.unknown": {
  "ko": "상태 확인 필요",
  "en": "Status unconfirmed",
  "lo": "ລໍຖ້າຢືນຢັນ"
},
  "domestic.verify": {
  "ko": "배송사 인증이 필요합니다. 배송사 사이트에서 확인하거나 담당자가 이력을 등록할 수 있습니다.",
  "en": "Carrier verification is required.",
  "lo": "ຕ້ອງຢືນຢັນໃນເວັບຂົນສົ່ງ."
},
  "domestic.voyage": {
  "ko": "항차",
  "en": "Voyage",
  "lo": "ຖ້ຽວ"
},
  "domestic.waybillCount": {
  "ko": "연결 송장",
  "en": "Linked waybills",
  "lo": "ໃບສົ່ງທີ່ເຊື່ອມ"
},
  "domestic.waybillHelp": {
  "ko": "같은 명세서의 송장번호를 + 버튼으로 추가하세요. 번호별 배송업체를 선택하고 함께 저장합니다.",
  "en": "Use + to add waybills for this statement. Select a carrier for each number and save together.",
  "lo": "ໃຊ້ປຸ່ມ + ເພີ່ມໃບສົ່ງໃນໃບລາຍການດຽວກັນ. ເລືອກຂົນສົ່ງແຕ່ລະເລກ ແລ້ວບັນທຶກພ້ອມກັນ."
},
  "domestic.when": {
  "ko": "처리 일시 (라오스 시간)",
  "en": "Event date/time (Laos)",
  "lo": "ວັນເວລາ (ເວລາລາວ)"
},
  "domestic.year": {
  "ko": "연도",
  "en": "Year",
  "lo": "ປີ"
},
  "domesticTracking": {
  "ko": "라오스 국내 배송 조회 & 관리 (e-commerce)",
  "en": "Laos Domestic Delivery Tracking & Management (e-commerce)",
  "lo": "ການຕິດຕາມແລະຈັດການການຂົນສົ່ງໃນປະເທດລາວ (e-commerce)"
},
  "edit": {
  "ko": "수정",
  "en": "Edit",
  "lo": "ແກ້ໄຂ"
},
  "email": {
  "ko": "이메일",
  "en": "Email",
  "lo": "ອີເມວ"
},
  "excel-management.fetchSettlement.additionalDiscount": {
  "ko": "추가 할인",
  "en": "Additional discount",
  "lo": "ສ່ວນຫຼຸດເພີ່ມ"
},
  "homeMenu": {
  "ko": "홈",
  "en": "Home",
  "lo": "ໜ້າຫຼັກ"
},
  "invoice": {
  "ko": "송장번호",
  "en": "Invoice",
  "lo": "ເລກໃບຂົນສົ່ງ"
},
  "layout.strong.lkGroup": {
  "ko": "LK Group",
  "en": "LK Group",
  "lo": "LK Group"
},
  "localDeliveries": {
  "ko": "시내.지방 배송 list 관리",
  "en": "City / Provincial Delivery List",
  "lo": "ຈັດການລາຍການຈັດສົ່ງໃນເມືອງ·ຕ່າງແຂວງ"
},
  "loginTitle": {
  "ko": "회원 로그인",
  "en": "Member Login",
  "lo": "ເຂົ້າລະບົບສະມາຊິກ"
},
  "logout": {
  "ko": "로그아웃",
  "en": "Sign Out",
  "lo": "ອອກຈາກລະບົບ"
},
  "name": {
  "ko": "이름",
  "en": "Name",
  "lo": "ຊື່"
},
  "notice": {
  "ko": "공지사항",
  "en": "Notice",
  "lo": "ແຈ້ງການ"
},
  "notices": {
  "ko": "공지사항 관리",
  "en": "Notice Management",
  "lo": "ຈັດການແຈ້ງການ"
},
  "parity.deletedRoutes": {
  "ko": "삭제 대기중",
  "en": "Pending deletion",
  "lo": "ລໍຖ້າລົບ"
},
  "password": {
  "ko": "비밀번호",
  "en": "Password",
  "lo": "ລະຫັດຜ່ານ"
},
  "passwordChange": {
  "ko": "비밀번호 변경",
  "en": "Change Password",
  "lo": "ປ່ຽນລະຫັດຜ່ານ"
},
  "phone": {
  "ko": "연락처",
  "en": "Phone",
  "lo": "ເບີໂທ"
},
  "quantity": {
  "ko": "수량",
  "en": "Qty",
  "lo": "ຈຳນວນ"
},
  "quote.addBox": {
  "ko": "박스 추가",
  "en": "Add box",
  "lo": "ເພີ່ມກ່ອງ"
},
  "quote.adminReply": {
  "ko": "관리자 회신",
  "en": "Team reply",
  "lo": "ພະນັກງານຕອບກັບ"
},
  "quote.box": {
  "ko": "박스",
  "en": "Box",
  "lo": "ກ່ອງ"
},
  "quote.content": {
  "ko": "내용",
  "en": "Details",
  "lo": "ເນື້ອຫາ"
},
  "quote.extra": {
  "ko": "기타 비용",
  "en": "Extra costs",
  "lo": "ຄ່າໃຊ້ຈ່າຍອື່ນ"
},
  "quote.hide": {
  "ko": "바로 삭제",
  "en": "Remove now",
  "lo": "ເອົາອອກດຽວນີ້"
},
  "quote.otherContact": {
  "ko": "기타 연락처",
  "en": "Other contact",
  "lo": "ຊ່ອງທາງຕິດຕໍ່ອື່ນ"
},
  "quote.packing": {
  "ko": "박스 포장",
  "en": "Box packing",
  "lo": "ຫຸ້ມຫໍ່ກ່ອງ"
},
  "quote.replied": {
  "ko": "회신 완료",
  "en": "Replied",
  "lo": "ຕອບແລ້ວ"
},
  "quote.title": {
  "ko": "운임 확인 및 견적 요청",
  "en": "Freight check & quote request",
  "lo": "ກວດຄ່າຂົນສົ່ງ ແລະ ຂໍລາຄາ"
},
  "quote.viewed": {
  "ko": "관리자 확인",
  "en": "Reviewed",
  "lo": "ກວດແລ້ວ"
},
  "quote.waiting": {
  "ko": "확인 전",
  "en": "Not yet reviewed",
  "lo": "ຍັງບໍ່ໄດ້ກວດ"
},
  "receipt-management.openReceiptCustomerEditor.appliesToAllCargoRowsIn": {
  "ko": "이 영수번호에 묶인 {count}개 화물에 동일하게 적용됩니다.",
  "en": "Applies to all {count} cargo rows in this receipt.",
  "lo": "ນຳໃຊ້ກັບສິນຄ້າ {count} ລາຍການໃນໃບຮັບນີ້."
},
  "receipt.customer": {
  "ko": "고객 정보 편집",
  "en": "Edit customer",
  "lo": "ແກ້ໄຂລູກຄ້າ"
},
  "receipt.discountName": {
  "ko": "추가 할인명",
  "en": "Additional discount name",
  "lo": "ຊື່ສ່ວນຫຼຸດເພີ່ມ"
},
  "receipt.name": {
  "ko": "비용 이름",
  "en": "Cost name",
  "lo": "ຊື່ຄ່າໃຊ້ຈ່າຍ"
},
  "receipt.percentInvalid": {
  "ko": "할인율은 0~100 사이로 입력해 주세요.",
  "en": "Enter a discount from 0 to 100.",
  "lo": "ໃສ່ສ່ວນຫຼຸດ 0–100."
},
  "route": {
  "ko": "운송 경로",
  "en": "Route",
  "lo": "ເສັ້ນທາງ"
},
  "routeNetwork_eta": {
  "ko": "도착 예정",
  "en": "Estimated arrival",
  "lo": "ຄາດວ່າຮອດ"
},
  "save": {
  "ko": "저장",
  "en": "Save",
  "lo": "ບັນທຶກ"
},
  "schedule": {
  "ko": "선적 일정",
  "en": "Shipping Schedule",
  "lo": "ຕາຕະລາງຂົນສົ່ງ"
},
  "search": {
  "ko": "검색",
  "en": "Search",
  "lo": "ຄົ້ນຫາ"
},
  "signup": {
  "ko": "회원가입",
  "en": "Sign Up",
  "lo": "ລົງທະບຽນ"
},
  "statement-preview.statementDocumentHtml.discount": {
  "ko": "할인",
  "en": "Discount",
  "lo": "ອັດຕາສ່ວນຫຼຸດ"
},
  "textManager.empty": {
  "ko": "검색 결과가 없습니다.",
  "en": "No matching text.",
  "lo": "ບໍ່ພົບຂໍ້ຄວາມ."
},
  "update": {
  "ko": "변경",
  "en": "Update",
  "lo": "ປ່ຽນ"
},
  "voyage": {
  "ko": "항차",
  "en": "Voyage",
  "lo": "ຖ້ຽວ"
},
  "year": {
  "ko": "년도",
  "en": "Year",
  "lo": "ປີ"
},
  "domestic.publicTitle": {
  "ko": "라오스 국내 배송 조회 (e-commerce)",
  "en": "Laos Domestic Delivery Tracking (e-commerce)",
  "lo": "ການຕິດຕາມການຂົນສົ່ງໃນປະເທດລາວ (e-commerce)"
}
};
